define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.y",
	"field-dayperiod": "დღის ნახევარი",
	"field-minute": "წუთი",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "გუშინ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ, y",
	"field-day-relative+-2": "გუშინწინ",
	"field-weekday": "კვირის დღე",
	"dateFormatItem-MMM": "LLL",
	"field-era": "ეპოქა",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "საათი",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM, y",
	"field-day-relative+0": "დღეს",
	"field-day-relative+1": "ხვალ",
	"field-day-relative+2": "ზეგ",
	"dateFormat-long": "d MMMM, y G",
	"field-zone": "დროის სარტყელი",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d.M.y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "წელი",
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "კვირა",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ, y",
	"field-month": "თვე",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM, y",
	"field-second": "წამი",
	"field-day": "დღე",
	"dateFormatItem-MEd": "E, d.M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"dateFormat-full": "EEEE, dd MMMM, y G",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "E, d.M.y",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);