define(
//begin v1.x content
{
	"dateFormatItem-yM": "M-y",
	"field-dayperiod": "a.m./p.m.",
	"field-minute": "Minuto",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "onte",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "antonte",
	"field-weekday": "Día da semana",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Era",
	"field-hour": "Hora",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "hoxe",
	"field-day-relative+1": "mañá",
	"field-day-relative+2": "pasadomañá",
	"dateFormat-long": "dd MMMM y G",
	"field-zone": "Fuso horario",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Semana pasada",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Este ano",
	"field-year-relative+1": "Seguinte ano",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "Ano pasado",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Ano",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Semana",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Esta semana",
	"field-week-relative+1": "Semana seguinte",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Este mes",
	"dateFormatItem-H": "HH",
	"field-month": "Mes",
	"field-month-relative+1": "Mes seguinte",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM, y",
	"field-second": "Segundo",
	"field-day": "Día",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"dateFormat-full": "EEEE dd MMMM y G",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Mes pasado",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);