define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"field-dayperiod": "Siang/Malam",
	"field-minute": "Menit",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Kemarin",
	"dateFormatItem-hms": "h.mm.ss a",
	"field-day-relative+-2": "Kemarin lusa",
	"field-weekday": "Hari dalam Seminggu",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "G y",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Era",
	"field-hour": "Jam",
	"dateFormatItem-y": "G y",
	"dateFormatItem-yyyy": "G y",
	"dateFormatItem-Ed": "E, d",
	"field-day-relative+0": "Hari Ini",
	"field-day-relative+1": "Besok",
	"field-day-relative+2": "Lusa",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Zona Waktu",
	"dateFormatItem-Hm": "HH.mm",
	"field-week-relative+-1": "Minggu lalu",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"field-year-relative+0": "Tahun ini",
	"field-year-relative+1": "Tahun depan",
	"field-year-relative+-1": "Tahun lalu",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"field-year": "Tahun",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Minggu",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-yyyyMEd": "E, d/M/y G",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Minggu ini",
	"field-week-relative+1": "Minggu berikutnya",
	"field-month-relative+0": "Bulan ini",
	"dateFormatItem-H": "HH",
	"field-month": "Bulan",
	"field-month-relative+1": "Bulan berikutnya",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"field-second": "Detik",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-day": "Hari",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-yyyyQQQ": "GGGGG y QQQ",
	"dateFormatItem-hm": "h.mm a",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormat-full": "EEEE, dd MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Bulan lalu",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);