define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "AM/PM",
	"field-minute": "Iminithi",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Izolo",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Usuku olwandulela olwayizolo",
	"field-weekday": "Usuku evikini",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "Isikhathi",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "Ihora",
	"dateFormatItem-y": "Y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Namhlanje",
	"field-day-relative+1": "Kusasa",
	"field-day-relative+2": "Usuku olulandela olakusasa",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Isikhathi sendawo",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Iviki eledlule",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Kulo nyaka",
	"field-year-relative+1": "Unyaka ozayo",
	"dateFormatItem-yMd": "M/d/y",
	"field-year-relative+-1": "Onyakeni odlule",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Unyaka",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Iviki",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "Leli viki",
	"field-week-relative+1": "Iviki elizayo",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Le nyanga",
	"dateFormatItem-H": "HH",
	"field-month": "Inyanga",
	"field-month-relative+1": "Inyanga ezayo",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d, y",
	"field-second": "Isekhondi",
	"field-day": "Usuku",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE dd MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Inyanga edlule",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);