define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "முற்பகல்/பிற்பகல்",
	"field-minute": "நிமிடம்",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "நேற்று",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+-2": "முந்தா நாள்",
	"field-weekday": "வார நாள்",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "காலம்",
	"field-hour": "மணி",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "இன்று",
	"field-day-relative+1": "நாளை",
	"field-day-relative+2": "நாளை மறுநாள்",
	"dateFormat-long": "d MMMM, y G",
	"field-zone": "மண்டலம்",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "கடந்த வாரம்",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "இந்த ஆண்டு",
	"field-year-relative+1": "அடுத்த வருடம்",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "கடந்த வருடம்",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "வருடம்",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "வாரம்",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "இந்த வாரம்",
	"field-week-relative+1": "அடுத்த வாரம்",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "இந்த மாதம்",
	"dateFormatItem-H": "HH",
	"field-month": "மாதம்",
	"field-month-relative+1": "அடுத்த மாதம்",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM, y",
	"field-second": "வினாடி",
	"field-day": "நாள்",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d-M-yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"dateFormat-full": "EEEE, d MMMM, y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "சென்ற மாதம்",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);