define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Muda wa siku",
	"field-minute": "Dakika",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Jana",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Mtondo",
	"field-weekday": "Siku ya wiki",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "Enzi",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "Saa",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Leo",
	"field-day-relative+1": "Kesho",
	"field-day-relative+2": "Kesho kutwa",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Majira ya saa",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Wiki iliyopita",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Mwaka huu",
	"field-year-relative+1": "Mwaka ujao",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "Mwaka uliopita",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Mwaka",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Wiki",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Wiki hii",
	"field-week-relative+1": "Wiki ijayo",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Mwezi huu",
	"dateFormatItem-H": "HH",
	"field-month": "Mwezi",
	"field-month-relative+1": "Mwezi ujao",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Sekunde",
	"field-day": "Siku",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Mwezi uliopita"
}
//end v1.x content
);