define(
//begin v1.x content
{
	"dateFormatItem-yM": "M-y",
	"field-dayperiod": "am/pm",
	"field-minute": "മിനിട്ട്",
	"dateFormatItem-MMMEd": "MMM d, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ഇന്നലെ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd-MM",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "മിനിഞ്ഞാന്ന്",
	"field-weekday": "ആഴ്ചയിലെ ദിവസം",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "കാലഘട്ടം",
	"field-hour": "മണിക്കൂർ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "ഇന്ന്",
	"field-day-relative+1": "നാളെ",
	"field-day-relative+2": "മറ്റന്നാൾ",
	"dateFormat-long": "G y, MMMM d",
	"field-zone": "മേഖല",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "കഴിഞ്ഞ ആഴ്ച",
	"dateFormat-medium": "G y, MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "ഈ വർഷം",
	"field-year-relative+1": "അടുത്തവർഷം",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "കഴിഞ്ഞ വർഷം",
	"dateFormatItem-yMMMM": "y MMMM",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "വർഷം",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "ആഴ്ച",
	"dateFormatItem-MMMMEd": "MMMM d, E",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "ഈ ആഴ്ച",
	"field-week-relative+1": "അടുത്ത ആഴ്ച",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month-relative+0": "ഈ മാസം",
	"dateFormatItem-H": "HH",
	"field-month": "മാസം",
	"field-month-relative+1": "അടുത്ത മാസം",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "സെക്കൻറ്",
	"field-day": "ദിവസം",
	"dateFormatItem-MEd": "M/d, E",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"dateFormatItem-yMMMEd": "y MMM d, E",
	"dateFormat-full": "G y, MMMM d, EEEE",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "d-M-y, E",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "കഴിഞ്ഞ മാസം",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);