define(
//begin v1.x content
{
	"dateFormatItem-yM": "M-y",
	"field-dayperiod": "AM/PM",
	"field-minute": "miniti",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "ʻaneafi",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "ʻaneheafi",
	"field-weekday": "ʻaho ʻo e uike",
	"dateFormatItem-MMM": "LLL",
	"field-era": "kuonga",
	"field-hour": "houa",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ʻaho⸍ni",
	"field-day-relative+1": "ʻapongipongi",
	"field-day-relative+2": "ʻahepongipongi",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "taimi fakavahe",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "taʻu",
	"field-week": "uike",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "māhina",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"field-second": "sekoni",
	"field-day": "ʻaho",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/yy GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);