define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM.y",
	"field-dayperiod": "ԿԱ/ԿՀ",
	"field-minute": "Րոպե",
	"dateFormatItem-MMMEd": "d MMM, E",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "Երեկ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y թ, QQQ",
	"field-day-relative+-2": "Երեկ չէ առաջի օրը",
	"field-weekday": "Շաբաթվա օր",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"field-era": "Թվարկություն",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-hour": "Ժամ",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d, ccc",
	"dateFormatItem-yMMM": "y թ. LLL",
	"field-day-relative+0": "Այսօր",
	"field-day-relative+1": "Վաղը",
	"field-day-relative+2": "Վաղը չէ մյուս օրը",
	"dateFormat-long": "dd MMMM, y թ. G",
	"field-zone": "Ժամային գոտի",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "dd MMM, y թ. G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "dd.MM.y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Տարի",
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "Շաբաթ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "y թ, QQQQ",
	"field-month": "Ամիս",
	"dateFormatItem-H": "H",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM, y թ.",
	"field-second": "Վայրկյան",
	"field-day": "Օր",
	"dateFormatItem-MEd": "dd.MM, E",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "d MMM, y թ., E",
	"dateFormat-full": "d MMMM, y թ. G, EEEE",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yMEd": "d.MM.y թ., E",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);