define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "пре подне/поподне",
	"field-minute": "минут",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "јуче",
	"dateFormatItem-hms": "hh.mm.ss a",
	"dateFormatItem-MMdd": "MM-dd",
	"dateFormatItem-yQQQ": "QQQ. y",
	"field-day-relative+-2": "прекјуче",
	"field-weekday": "дан у недељи",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "ера",
	"field-hour": "час",
	"dateFormatItem-y": "y.",
	"dateFormatItem-MMMdd": "dd.MMM",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-yMMdd": "dd.MM.y",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y.",
	"field-day-relative+0": "данас",
	"field-day-relative+1": "сутра",
	"field-day-relative+2": "прекосутра",
	"dateFormat-long": "dd. MMMM y. G",
	"field-zone": "зона",
	"dateFormatItem-Hm": "HH.mm",
	"field-week-relative+-1": "Прошле недеље",
	"dateFormat-medium": "dd.MM.y. G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"field-year-relative+0": "Ове године",
	"field-year-relative+1": "Следеће године",
	"dateFormatItem-yMd": "d. M. y.",
	"field-year-relative+-1": "Прошле године",
	"dateFormatItem-yMMMM": "MMMM y.",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "година",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "недеља",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "Ове недеље",
	"field-week-relative+1": "Следеће недеље",
	"dateFormatItem-yQQQQ": "QQQQ. y",
	"field-month-relative+0": "Овог месеца",
	"dateFormatItem-H": "HH",
	"field-month": "месец",
	"field-month-relative+1": "Следећег месеца",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d. MMM y.",
	"field-second": "секунд",
	"field-day": "дан",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "hh.mm a",
	"dateFormat-short": "d.M.yy. GGGGG",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"dateFormat-full": "EEEE, dd. MMMM y. G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d. M. y.",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Прошлог месеца",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);