define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM.y",
	"field-dayperiod": "Частина доби",
	"field-minute": "Хвилина",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Вчора",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd.MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Позавчора",
	"field-weekday": "День тижня",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Ера",
	"field-hour": "Година",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "LLL y",
	"field-day-relative+0": "Сьогодні",
	"field-day-relative+1": "Завтра",
	"field-day-relative+2": "Післязавтра",
	"dateFormat-long": "d MMMM y 'р'. G",
	"field-zone": "Зона",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Минулого тижня",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Цього року",
	"field-year-relative+1": "Наступного року",
	"dateFormatItem-yMd": "dd.MM.y",
	"field-year-relative+-1": "Минулого року",
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Рік",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"field-week": "Тиждень",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Цього тижня",
	"dateFormatItem-HHmm": "HH:mm",
	"field-week-relative+1": "Наступного тижня",
	"dateFormatItem-yQQQQ": "QQQQ y 'р'.",
	"field-month-relative+0": "Цього місяця",
	"dateFormatItem-H": "HH",
	"field-month": "Місяць",
	"field-month-relative+1": "Наступного місяця",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Секунда",
	"field-day": "День",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y 'р'. G",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yMEd": "E, dd.MM.y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Минулого місяця",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);