define(
//begin v1.x content
{
	"field-dayperiod": "Частина доби",
	"dayPeriods-format-wide-pm": "пп",
	"field-minute": "Хвилина",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "Вчора",
	"field-weekday": "День тижня",
	"field-day-relative+-2": "Позавчора",
	"field-era": "Ера",
	"field-hour": "Година",
	"dayPeriods-format-wide-am": "дп",
	"quarters-standAlone-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"dateFormatItem-y": "y",
	"months-standAlone-abbr": [
		"Тішри",
		"Марчешван",
		"Числьов",
		"Тебет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нісан",
		"Іар",
		"Сиван",
		"Таммуз",
		"Аб",
		"Елул"
	],
	"dateFormatItem-Ed": "E, d",
	"field-day-relative+0": "Сьогодні",
	"field-day-relative+1": "Завтра",
	"days-standAlone-narrow": [
		"Н",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"field-day-relative+2": "Післязавтра",
	"dateFormat-long": "d MMMM y 'р'. G",
	"field-zone": "Зона",
	"field-week-relative+-1": "Минулого тижня",
	"dateFormat-medium": "d MMM y G",
	"field-year-relative+0": "Цього року",
	"field-year-relative+1": "Наступного року",
	"quarters-standAlone-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"field-year-relative+-1": "Минулого року",
	"field-year": "Рік",
	"months-standAlone-wide": [
		"Тішри",
		"Марчешван",
		"Числьов",
		"Тебет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нісан",
		"Іар",
		"Сиван",
		"Таммуз",
		"Аб",
		"Елул"
	],
	"field-week": "Тиждень",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Цього тижня",
	"field-week-relative+1": "Наступного тижня",
	"months-format-abbr": [
		"Тішри",
		"Марчешван",
		"Числьов",
		"Тебет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нісан",
		"Іар",
		"Сиван",
		"Таммуз",
		"Аб",
		"Елул"
	],
	"field-month-relative+0": "Цього місяця",
	"field-month": "Місяць",
	"field-month-relative+1": "Наступного місяця",
	"quarters-format-abbr": [
		"I кв.",
		"II кв.",
		"III кв.",
		"IV кв."
	],
	"days-format-abbr": [
		"Нд",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"field-second": "Секунда",
	"field-day": "День",
	"dateFormatItem-MEd": "E, dd.MM",
	"days-standAlone-short": [
		"Нд",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormat-full": "EEEE, d MMMM y 'р'. G",
	"dateFormatItem-Md": "dd.MM",
	"months-format-wide": [
		"Тішри",
		"Марчешван",
		"Числьов",
		"Тебет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нісан",
		"Іар",
		"Сиван",
		"Таммуз",
		"Аб",
		"Елул"
	],
	"days-format-short": [
		"Нд",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"months-format-wide-leap": "Адар II",
	"field-month-relative+-1": "Минулого місяця",
	"quarters-format-wide": [
		"I квартал",
		"II квартал",
		"III квартал",
		"IV квартал"
	],
	"days-format-wide": [
		"Неділя",
		"Понеділок",
		"Вівторок",
		"Середа",
		"Четвер",
		"Пʼятниця",
		"Субота"
	]
}
//end v1.x content
);