define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, MMM d, y G",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} 'at' {0}",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dateTimeFormats-appendItem-Year": "{0} {1}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-y": "y G",
	"timeFormat-full": "h:mm:ss a zzzz",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-GyMMMd": "MMM d, y G",
	"dateFormat-long": "d MMMM, y G",
	"timeFormat-medium": "h:mm:ss a",
	"dateFormat-medium": "d MMM, y G",
	"dayPeriods-format-narrow-pm": "p",
	"field-year-relative+0": "This Year",
	"field-year-relative+1": "Next Year",
	"dateFormatItem-yMd": "d/M/y GGGGG",
	"field-year-relative+-1": "Last Year",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dayPeriods-format-narrow-am": "a",
	"dateTimeFormat-long": "{1} 'at' {0}",
	"dateFormatItem-yyyyMd": "M/d/y GGGGG",
	"dateFormatItem-yyyyMMMd": "MMM d, y G",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-yyyyMEd": "E, M/d/y GGGGG",
	"field-week-relative+1": "Next Week",
	"timeFormat-long": "h:mm:ss a z",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec"
	],
	"timeFormat-short": "h:mm a",
	"dateFormatItem-yMMMd": "d MMM, y G",
	"dateFormatItem-GyMMMEd": "E, MMM d, y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormat-short": "d/M/yy GGGGG",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM, y G",
	"dateFormat-full": "EEEE, d MMMM, y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, d/M/y GGGGG",
	"months-format-wide": [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December"
	],
	"days-format-short": [
		"Su",
		"Mo",
		"Tu",
		"We",
		"Th",
		"Fr",
		"Sa"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateTimeFormats-appendItem-Era": "{0} {1}",
	"quarters-format-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"days-format-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	]
}
//end v1.x content
);