define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "ಪೂರ್ವಾಹ್ನ/ಅಪರಾಹ್ನ",
	"field-minute": "ನಿಮಿಷ",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ನಿನ್ನೆ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+-2": "ಮೊನ್ನೆ",
	"field-weekday": "ವಾರದ ದಿನ",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "ಯುಗ",
	"field-hour": "ಗಂಟೆ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ಇಂದು",
	"field-day-relative+1": "ನಾಳೆ",
	"field-day-relative+2": "ನಾಡಿದ್ದು",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "ಸಮಯ ವಲಯ:",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "ಕೊನೆಯ ವಾರ",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "ಈ ವರ್ಷ",
	"field-year-relative+1": "ಮುಂದಿನ ವರ್ಷ",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "ಕೊನೆಯ ವರ್ಷ",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ವರ್ಷ",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "ವಾರ",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "ಈ ವಾರ",
	"field-week-relative+1": "ಮುಂದಿನ ವಾರ",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "ಈ ತಿಂಗಳು",
	"dateFormatItem-H": "HH",
	"field-month": "ತಿಂಗಳು",
	"field-month-relative+1": "ಮುಂದಿನ ತಿಂಗಳು",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d, MMM, y",
	"field-second": "ಸೆಕೆಂಡ್",
	"field-day": "ದಿನ",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d-M-yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "ಕಳೆದ ತಿಂಗಳು",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);