define(
//begin v1.x content
{
	"field-dayperiod": "iki pietų / po pietų",
	"dayPeriods-format-wide-pm": "popiet",
	"field-minute": "minutė",
	"field-day-relative+-1": "vakar",
	"field-weekday": "savaitės diena",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-day-relative+-2": "užvakar",
	"days-standAlone-wide": [
		"sekmadienis",
		"pirmadienis",
		"antradienis",
		"trečiadienis",
		"ketvirtadienis",
		"penktadienis",
		"šeštadienis"
	],
	"months-standAlone-narrow": [
		"S",
		"V",
		"K",
		"B",
		"G",
		"B",
		"L",
		"R",
		"R",
		"S",
		"L",
		"G"
	],
	"field-era": "era",
	"field-hour": "valanda",
	"dayPeriods-format-wide-am": "priešpiet",
	"quarters-standAlone-abbr": [
		"I ketv.",
		"II ketv.",
		"III ketv.",
		"IV ketv."
	],
	"dateFormatItem-y": "y",
	"months-standAlone-abbr": [
		"saus.",
		"vas.",
		"kov.",
		"bal.",
		"geg.",
		"birž.",
		"liep.",
		"rugp.",
		"rugs.",
		"spal.",
		"lapkr.",
		"gruod."
	],
	"dateFormatItem-Ed": "E, d",
	"field-day-relative+0": "šiandien",
	"field-day-relative+1": "rytoj",
	"days-standAlone-narrow": [
		"S",
		"P",
		"A",
		"T",
		"K",
		"P",
		"Š"
	],
	"field-day-relative+2": "poryt",
	"dateFormat-long": "G y 'm'. MMMM d 'd'.",
	"field-zone": "laiko juosta",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "praėjusią savaitę",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "šiais metais",
	"field-year-relative+1": "kitais metais",
	"quarters-standAlone-wide": [
		"I ketvirtis",
		"II ketvirtis",
		"III ketvirtis",
		"IV ketvirtis"
	],
	"field-year-relative+-1": "praėjusiais metais",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "metai",
	"months-standAlone-wide": [
		"sausis",
		"vasaris",
		"kovas",
		"balandis",
		"gegužė",
		"birželis",
		"liepa",
		"rugpjūtis",
		"rugsėjis",
		"spalis",
		"lapkritis",
		"gruodis"
	],
	"field-week": "savaitė",
	"field-week-relative+0": "šią savaitę",
	"field-week-relative+1": "kitą savaitę",
	"months-format-abbr": [
		"saus.",
		"vas.",
		"kov.",
		"bal.",
		"geg.",
		"birž.",
		"liep.",
		"rugp.",
		"rugs.",
		"spal.",
		"lapkr.",
		"gruod."
	],
	"field-month-relative+0": "šį mėnesį",
	"field-month": "mėnuo",
	"field-month-relative+1": "kitą mėnesį",
	"dateFormatItem-H": "HH",
	"quarters-format-abbr": [
		"I k.",
		"II k.",
		"III k.",
		"IV k."
	],
	"days-format-abbr": [
		"sk",
		"pr",
		"an",
		"tr",
		"kt",
		"pn",
		"št"
	],
	"dateFormatItem-M": "LL",
	"days-format-narrow": [
		"S",
		"P",
		"A",
		"T",
		"K",
		"P",
		"Š"
	],
	"field-second": "sekundė",
	"field-day": "diena",
	"dateFormatItem-MEd": "M-d, E",
	"months-format-narrow": [
		"S",
		"V",
		"K",
		"B",
		"G",
		"B",
		"L",
		"R",
		"R",
		"S",
		"L",
		"G"
	],
	"days-standAlone-short": [
		"Sk",
		"Pr",
		"An",
		"Tr",
		"Kt",
		"Pn",
		"Št"
	],
	"dateFormatItem-hm": "h:mm a",
	"days-standAlone-abbr": [
		"sk",
		"pr",
		"an",
		"tr",
		"kt",
		"pn",
		"št"
	],
	"dayPeriods-format-abbr-pm": "pop.",
	"dateFormat-full": "y G, MMMM d, EEEE",
	"dateFormatItem-Md": "MM-d",
	"months-format-wide": [
		"sausis",
		"vasaris",
		"kovas",
		"balandis",
		"gegužė",
		"birželis",
		"liepa",
		"rugpjūtis",
		"rugsėjis",
		"spalis",
		"lapkritis",
		"gruodis"
	],
	"dayPeriods-format-abbr-am": "pr.p.",
	"days-format-short": [
		"Sk",
		"Pr",
		"An",
		"Tr",
		"Kt",
		"Pn",
		"Št"
	],
	"field-month-relative+-1": "praėjusį mėnesį",
	"quarters-format-wide": [
		"I ketvirtis",
		"II ketvirtis",
		"III ketvirtis",
		"IV ketvirtis"
	],
	"days-format-wide": [
		"sekmadienis",
		"pirmadienis",
		"antradienis",
		"trečiadienis",
		"ketvirtadienis",
		"penktadienis",
		"šeštadienis"
	],
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);