define(
//begin v1.x content
{
	"field-second": "sekundė",
	"field-year-relative+-1": "praėjusiais metais",
	"field-week": "savaitė",
	"field-month-relative+-1": "praėjusį mėnesį",
	"field-day-relative+-1": "vakar",
	"field-day-relative+-2": "užvakar",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"field-year": "metai",
	"field-week-relative+0": "šią savaitę",
	"field-week-relative+1": "kitą savaitę",
	"field-minute": "minutė",
	"field-week-relative+-1": "praėjusią savaitę",
	"field-day-relative+0": "šiandien",
	"field-hour": "valanda",
	"field-day-relative+1": "rytoj",
	"field-day-relative+2": "poryt",
	"field-day": "diena",
	"field-month-relative+0": "šį mėnesį",
	"field-month-relative+1": "kitą mėnesį",
	"field-dayperiod": "iki pietų / po pietų",
	"field-month": "mėnuo",
	"field-era": "era",
	"field-year-relative+0": "šiais metais",
	"field-year-relative+1": "kitais metais",
	"field-weekday": "savaitės diena",
	"field-zone": "laiko juosta"
}
//end v1.x content
);