define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-MM",
	"field-dayperiod": "iki pietų / po pietų",
	"field-minute": "minutė",
	"dateFormatItem-MMMEd": "MMM d, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "vakar",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-MMdd": "MM.dd",
	"field-day-relative+-2": "užvakar",
	"field-weekday": "savaitės diena",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "era",
	"field-hour": "valanda",
	"dateFormatItem-y": "y",
	"dateFormatItem-MMMdd": "MMM-dd",
	"dateFormatItem-yMM": "y.MM",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "MMM, y",
	"field-day-relative+0": "šiandien",
	"field-day-relative+1": "rytoj",
	"field-day-relative+2": "poryt",
	"dateFormat-long": "G y 'm'. MMMM d 'd'.",
	"field-zone": "laiko juosta",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "praėjusią savaitę",
	"dateFormat-medium": "G y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "šiais metais",
	"field-year-relative+1": "kitais metais",
	"dateFormatItem-yMd": "y-M-d",
	"field-year-relative+-1": "praėjusiais metais",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "metai",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "savaitė",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "šią savaitę",
	"field-week-relative+1": "kitą savaitę",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month-relative+0": "šį mėnesį",
	"dateFormatItem-H": "HH",
	"field-month": "mėnuo",
	"field-month-relative+1": "kitą mėnesį",
	"dateFormatItem-M": "LL",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "sekundė",
	"field-day": "diena",
	"dateFormatItem-MEd": "M-d, E",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "G y 'm'. MMMM d 'd'., EEEE",
	"dateFormatItem-Md": "MM-d",
	"dateFormatItem-yMEd": "E, y-MM-d",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "praėjusį mėnesį",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);