define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "AM/PM",
	"field-minute": "నిమిషము",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "నిన్న",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+-2": "మొన్న",
	"field-weekday": "వారంలో రోజు",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "యుగం, శకము",
	"field-hour": "గంట",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ఈ రోజు",
	"field-day-relative+1": "రేపు",
	"field-day-relative+2": "ఎల్లుండి",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "మండలం",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "గత వారం",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "ఈ సంవత్సరం",
	"field-year-relative+1": "తర్వాతి సంవత్సరం",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "మునుపటి సంవత్సరం",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "సంవత్సరం",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "వారము",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "ఈ వారం",
	"field-week-relative+1": "తదుపరి వారం",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "ఈ నెల",
	"dateFormatItem-H": "HH",
	"field-month": "నెల",
	"field-month-relative+1": "తర్వాతి నెల",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d, MMM y",
	"field-second": "క్షణం",
	"field-day": "దినం",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd-MM-yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d, MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "గత నెల",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);