define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "رات/صبح",
	"field-minute": "منٹ",
	"dateFormatItem-MMMEd": "E، d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "گزشتہ کل",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "گزشتہ پرسوں",
	"field-weekday": "ہفتے کا دن",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "عہد",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "گھنٹہ",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "آج",
	"field-day-relative+1": "آئندہ کل",
	"field-day-relative+2": "آنے والا پرسوں",
	"dateFormat-long": "d MMMM، y G",
	"field-zone": "منطقہ وقت",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "پچھلے ہفتہ",
	"dateFormat-medium": "d MMM، y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "اس سال",
	"field-year-relative+1": "اگلے سال",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "پچھلے سال",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "سال",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "ہفتہ",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "اس ہفتہ",
	"field-week-relative+1": "اگلے ہفتہ",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "اس مہینہ",
	"dateFormatItem-H": "HH",
	"field-month": "مہینہ",
	"field-month-relative+1": "اگلے مہینہ",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM، y",
	"field-second": "سیکنڈ",
	"field-day": "دن",
	"dateFormatItem-MEd": "E، d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/yy GGGGG",
	"dateFormatItem-yMMMEd": "E، d MMM، y",
	"dateFormat-full": "EEEE، d MMMM، y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E، d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "پچھلے مہینہ",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);