define(
//begin v1.x content
{
	"field-dayperiod": "رات/صبح",
	"dayPeriods-format-wide-pm": "بعد دوپہر",
	"field-minute": "منٹ",
	"dateFormatItem-MMMEd": "E، d MMM",
	"field-day-relative+-1": "گزشتہ کل",
	"field-weekday": "ہفتے کا دن",
	"field-day-relative+-2": "گزشتہ پرسوں",
	"field-era": "عہد",
	"field-hour": "گھنٹہ",
	"dayPeriods-format-wide-am": "قبل دوپہر",
	"dateFormatItem-y": "y",
	"timeFormat-full": "h:mm:ss a zzzz",
	"months-standAlone-abbr": [
		"محرم",
		"صفر",
		"ر بیع الاول",
		"ر بیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذوالقعدۃ",
		"ذوالحجۃ"
	],
	"dateFormatItem-Ed": "d E",
	"field-day-relative+0": "آج",
	"field-day-relative+1": "آئندہ کل",
	"field-day-relative+2": "آنے والا پرسوں",
	"dateFormat-long": "d MMMM، y G",
	"timeFormat-medium": "h:mm:ss a",
	"field-zone": "منطقہ وقت",
	"field-week-relative+-1": "پچھلے ہفتہ",
	"dateFormat-medium": "d MMM، y G",
	"field-year-relative+0": "اس سال",
	"field-year-relative+1": "اگلے سال",
	"field-year-relative+-1": "پچھلے سال",
	"field-year": "سال",
	"months-standAlone-wide": [
		"محرم",
		"صفر",
		"ر بیع الاول",
		"ر بیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذوالقعدۃ",
		"ذوالحجۃ"
	],
	"field-week": "ہفتہ",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "اس ہفتہ",
	"field-week-relative+1": "اگلے ہفتہ",
	"timeFormat-long": "h:mm:ss a z",
	"months-format-abbr": [
		"محرم",
		"صفر",
		"ر بیع الاول",
		"ر بیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذوالقعدۃ",
		"ذوالحجۃ"
	],
	"field-month-relative+0": "اس مہینہ",
	"field-month": "مہینہ",
	"field-month-relative+1": "اگلے مہینہ",
	"timeFormat-short": "h:mm a",
	"field-second": "سیکنڈ",
	"field-day": "دن",
	"dateFormatItem-MEd": "E، d/M",
	"days-standAlone-short": [
		"اتوار",
		"سوموار",
		"منگل",
		"بدھ",
		"جمعرات",
		"جمعہ",
		"ہفتہ"
	],
	"dayPeriods-format-abbr-pm": "بعد دوپہر",
	"dateFormat-short": "d/M/yy GGGGG",
	"dateFormat-full": "EEEE، d MMMM، y G",
	"dateFormatItem-Md": "d/M",
	"months-format-wide": [
		"محرم",
		"صفر",
		"ر بیع الاول",
		"ر بیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذوالقعدۃ",
		"ذوالحجۃ"
	],
	"dayPeriods-format-abbr-am": "قبل دوپہر",
	"days-format-short": [
		"اتوار",
		"سوموار",
		"منگل",
		"بدھ",
		"جمعرات",
		"جمعہ",
		"ہفتہ"
	],
	"field-month-relative+-1": "پچھلے مہینہ",
	"quarters-format-wide": [
		"پہلی سہ ماہی",
		"دوسری سہ ماہی",
		"تیسری سہ ماہی",
		"چوتهی سہ ماہی"
	],
	"days-format-wide": [
		"اتوار",
		"پیر",
		"منگل",
		"بده",
		"جمعرات",
		"جمعہ",
		"ہفتہ"
	]
}
//end v1.x content
);