define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "ເຊົ້າ/ແລງ",
	"dayPeriods-format-wide-pm": "ຫຼັງທ່ຽງ",
	"field-minute": "ນາທີ",
	"dateFormatItem-MMMEd": "E MMM d",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "ວານນີ້",
	"field-weekday": "ມື້ຂອງອາທິດ",
	"dateFormatItem-hms": "H:mm:ss",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "ມື້ກ່ອນ",
	"days-standAlone-wide": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateTimeFormat-short": "{1}, {0}",
	"field-era": "ສະໄໝ",
	"field-hour": "ຊົ່ວໂມງ",
	"dayPeriods-format-wide-am": "ກ່ອນທ່ຽງ",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-y": "y",
	"timeFormat-full": "H ໂມງ m ນາທີ ss ວິນາທີ zzzz",
	"months-standAlone-abbr": [
		"ມຸຮັດ",
		"ເຄາະ",
		"ຮອກບີ 1",
		"ຮອກບີ 2",
		"ນຸມາ 1",
		"ນຸມາ 2",
		"ເຮາະ",
		"ຊາ",
		"ເຮາະມະ",
		"ເຊົາ",
		"ຊຸລກິອຸ",
		"ຊຸລຫິຈ"
	],
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ມື້ນີ້",
	"field-day-relative+1": "ມື້ອື່ນ",
	"days-standAlone-narrow": [
		"ທ",
		"ຈ",
		"ຄ",
		"ພຸ",
		"ພ",
		"ສຸ",
		"ສ"
	],
	"eraAbbr": [
		"AH"
	],
	"field-day-relative+2": "ມື້ຮື",
	"dateFormat-long": "y MMMM d",
	"timeFormat-medium": "H:mm:ss",
	"field-zone": "ເວລາຕາມເຂດ",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"quarters-standAlone-wide": [
		"ໄຕມາດ1",
		"ໄຕມາດ2",
		"ໄຕມາດ3",
		"ໄຕມາດ4"
	],
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ປີ",
	"dateTimeFormat-long": "{1}, {0}",
	"months-standAlone-wide": [
		"ມຸຣະຮອມ",
		"ຊາຟາຣ",
		"ຮາບີ 1",
		"ຮາບີ 2",
		"ຈຸມາດາ 1",
		"ຈຸມາດາ 2",
		"ຮາຈັບ",
		"ຊະບານ",
		"ຮາມາດອນ",
		"ເຊົາວັດ",
		"ດຸອັດກິດະ",
		"ດຸອັດກິຈະ"
	],
	"field-week": "ອາທິດ",
	"dateFormatItem-MMMd": "d MMM",
	"months-format-abbr": [
		"ມຸຮັດ",
		"ເຄາະ",
		"ຮອດບີ 1",
		"ຮອກບີ 2",
		"ນຸມາ 1",
		"ນຸມາ 2",
		"ເຮາະ",
		"ຊະອ໌",
		"ເຮາະມະ",
		"ເຊົາ",
		"ຊຸລກິອຸ",
		"ຊຸລຫິຈ"
	],
	"timeFormat-long": "H ໂມງ m ນາທີ ss ວິນາທີ z",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "ເດືອນ",
	"dateFormatItem-H": "H",
	"timeFormat-short": "H:mm",
	"quarters-format-abbr": [
		"ຄິວ1",
		"ຄີວ2",
		"ຄີວ3",
		"ຄິວ4"
	],
	"days-format-abbr": [
		"ອາ.",
		"ຈ.",
		"ອ.",
		"ພ.",
		"ພຫ.",
		"ສກ.",
		"ສ."
	],
	"dateFormatItem-M": "L",
	"days-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"field-second": "ວິນາທີ",
	"field-day": "ມື້",
	"dateFormatItem-MEd": "E, d/M",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"days-standAlone-short": [
		"ອ.ທ.",
		"ຈັນ",
		"ຄ",
		"ພ",
		"ພຫ",
		"ສ",
		"ເສົາ"
	],
	"dateFormatItem-hm": "h mm a",
	"days-standAlone-abbr": [
		"ທ.",
		"ຈ.",
		"ອ.",
		"ພ.",
		"ພຫ.",
		"ສກ.",
		"ສ."
	],
	"dateFormat-short": "y-MM-dd",
	"dateFormatItem-yMMMEd": "E,MMM d,y",
	"dateFormat-full": "EEEE, y MMMM dd",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E M/d/y",
	"months-format-wide": [
		"ມຸຣະຮອມ",
		"ຊາຟາຣ",
		"ຮາບີ 1",
		"ຮາບີ 2",
		"ຈຸມາດາ 1",
		"ຈຸມາດາ 2",
		"ຮາຈັບ",
		"ຊະບານ",
		"ຮາມາດອນ",
		"ເຊົາວັດ",
		"ດຸອັດກິດະ",
		"ດຸອັດກິຈະ"
	],
	"days-format-short": [
		"ອທ.",
		"ຈ.",
		"ອ.",
		"ພ.",
		"ພຫ.",
		"ສກ.",
		"ສ."
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"ໄຕມາດ1",
		"ໄຕມາດ2",
		"ໄຕມາດ3",
		"ໄຕມາດ4"
	],
	"days-format-wide": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"dateFormatItem-h": "ha"
}
//end v1.x content
);