define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y G",
	"field-dayperiod": "PG/PTG",
	"field-minute": "Minit",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "Semalam",
	"field-weekday": "Hari dalam Minggu",
	"field-day-relative+-2": "Hari sebelum semalam",
	"field-era": "Era",
	"field-hour": "Jam",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "MMM y G",
	"field-day-relative+0": "Hari ini",
	"field-day-relative+1": "Esok",
	"field-day-relative+2": "Hari selepas esok",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Zon Waktu",
	"field-week-relative+-1": "Minggu lepas",
	"dateFormat-medium": "dd/MM/y G",
	"field-year-relative+0": "Tahun ini",
	"field-year-relative+1": "Tahun depan",
	"field-year-relative+-1": "Tahun lepas",
	"field-year": "Tahun",
	"field-week": "Minggu",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Minggu ini",
	"field-week-relative+1": "Minggu seterusnya",
	"field-month-relative+0": "Bulan ini",
	"field-month": "Bulan",
	"field-month-relative+1": "Bulan seterusnya",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-yMMMd": "d MMM y G",
	"field-second": "Kedua",
	"field-day": "Hari",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormat-short": "d/MM/y G",
	"dateFormatItem-yMMMEd": "E, d MMM y G",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y G",
	"field-month-relative+-1": "Bulan lalu"
}
//end v1.x content
);