define(
//begin v1.x content
{
	"dateFormatItem-yM": "M y",
	"field-dayperiod": "f.m./e.m.-val",
	"field-minute": "minutt",
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "i går",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "i forgårs",
	"dateFormatItem-MMdd": "d.M.",
	"field-weekday": "vekedag",
	"field-era": "æra",
	"field-hour": "time",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgon",
	"field-day-relative+2": "i overmorgon",
	"dateFormat-long": "d. MMMM y G",
	"field-zone": "sone",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d.M.y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "år",
	"field-week": "veke",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "månad",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-yMMMd": "d. MMM y",
	"field-second": "sekund",
	"field-day": "dag",
	"dateFormatItem-MEd": "E d.M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E d. MMM y",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "E d.M.y",
	"dateFormatItem-d": "d."
}
//end v1.x content
);