define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Dayperiod",
	"field-minute": "Minuto",
	"dateFormatItem-MMMEd": "E MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Kahapon",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Araw bago ang kahapon",
	"field-weekday": "Araw ng Linggo",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Era",
	"field-hour": "Oras",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Ngayon",
	"field-day-relative+1": "Bukas",
	"field-day-relative+2": "Araw pagkatapos ng kahapon",
	"dateFormat-long": "MMMM d, y G",
	"field-zone": "Zone",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Nakaraang Linggo",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Sa taong ito",
	"field-year-relative+1": "Susunod na taon",
	"dateFormatItem-yMd": "M/d/y",
	"field-year-relative+-1": "Nakaraang taon",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Taon",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Linggo",
	"dateFormatItem-MMMMEd": "E MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "Sa linggong ito",
	"field-week-relative+1": "Susunod na linggo",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month-relative+0": "Ngayon buwang ito",
	"dateFormatItem-H": "HH",
	"field-month": "Buwan",
	"field-month-relative+1": "Susunod na buwan",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d, y",
	"field-second": "Segundo",
	"field-day": "Araw",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "M/d/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, MMMM dd y G",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Nakaraang buwan",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);