define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "পূর্বাহ্ণ/অপরাহ্ণ",
	"field-minute": "মিনিট",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "গতকাল",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd-MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "গত পরশু",
	"field-weekday": "সপ্তাহের দিন",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "যুগ",
	"field-hour": "ঘন্টা",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "আজ",
	"field-day-relative+1": "আগামীকাল",
	"field-day-relative+2": "আগামী পরশু",
	"dateFormat-long": "d MMMM, y G",
	"field-zone": "এলাকা",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "গত সপ্তাহ",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "এই বছর",
	"field-year-relative+1": "পরের বছর",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "আগের বছর",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "বছর",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "সপ্তাহ",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "এই সপ্তাহ",
	"field-week-relative+1": "পরবর্তী সপ্তাহ",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "এই মাস",
	"dateFormatItem-H": "HH",
	"field-month": "মাস",
	"field-month-relative+1": "পরের মাস",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM, y",
	"field-second": "সেকেন্ড",
	"field-day": "দিন",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"dateFormat-full": "EEEE, d MMMM, y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "গত মাস",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);