define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "SA/CH",
	"field-minute": "Phút",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"dateTimeFormat-full": "{0} {1}",
	"field-day-relative+-1": "Ngày hôm qua",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd-MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Ngày hôm kia",
	"field-weekday": "Ngày trong tuần",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{0} {1}",
	"dateTimeFormat-medium": "{0} {1}",
	"field-era": "Thời đại",
	"field-hour": "Giờ",
	"dateFormatItem-y": "'Năm' y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "E, dd",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"field-zone": "Múi giờ",
	"dateFormatItem-Hm": "H:mm",
	"field-week-relative+-1": "Tuần trước",
	"dateFormat-medium": "dd-MM-y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"field-year-relative+0": "Năm nay",
	"field-year-relative+1": "Năm sau",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "Năm ngoái",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Năm",
	"dateTimeFormat-long": "{0} {1}",
	"field-week": "Tuần",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"dateFormatItem-MMMd": "dd MMM",
	"field-week-relative+0": "Tuần này",
	"field-week-relative+1": "Tuần sau",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Tháng này",
	"dateFormatItem-H": "HH",
	"field-month": "Tháng",
	"field-month-relative+1": "Tháng sau",
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "dd MMM, y",
	"field-second": "Giây",
	"field-day": "Ngày",
	"dateFormatItem-MEd": "E, dd-M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, dd MMM y",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y G",
	"dateFormatItem-Md": "dd-M",
	"dateFormatItem-yMEd": "E, dd-M-y",
	"dateFormatItem-d": "'Ngày' dd",
	"field-month-relative+-1": "Tháng trước",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);