define(
//begin v1.x content
{
	"dateFormatItem-yM": "M. y",
	"field-dayperiod": "f.h./e.h.",
	"field-minute": "mínúta",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "í gær",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "fyrir tveimur dögum",
	"field-weekday": "vikudagur",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "tímabil",
	"field-hour": "klukkustund",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "e d.",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "í dag",
	"field-day-relative+1": "á morgun",
	"field-day-relative+2": "eftir tvo daga",
	"dateFormat-long": "d. MMMM y G",
	"field-zone": "svæði",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Í síðustu viku",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Á þessu ári",
	"field-year-relative+1": "Á næsta ári",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "Á síðasta ári",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ár",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "vika",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "Í þessari viku",
	"field-week-relative+1": "Í næstu viku",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Í þessum mánuði",
	"dateFormatItem-H": "HH",
	"field-month": "mánuður",
	"field-month-relative+1": "Í næsta mánuði",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-M": "L.",
	"dateFormatItem-yMMMd": "d MMM, y",
	"field-second": "sekúnda",
	"field-day": "dagur",
	"dateFormatItem-MEd": "E d.M.",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d.M.y GGGGG",
	"dateFormatItem-yMMMEd": "E d. MMM y",
	"dateFormat-full": "EEEE, d. MMMM y G",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Í síðasta mánuði",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);