define(
//begin v1.x content
{
	"days-standAlone-short": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-weekday": "dan u nedelji",
	"$locale": "sr-latn",
	"dateFormatItem-yQQQ": "QQQ. y",
	"dateFormatItem-yMEd": "E, d. M. y.",
	"dateFormatItem-MMMEd": "E d. MMM",
	"eraNarrow": [
		"p. n. e.",
		"n. e."
	],
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-MMMdd": "dd.MMM",
	"days-format-short": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"dateFormat-long": "dd. MMMM y.",
	"months-format-wide": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"jun",
		"jul",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"dayPeriods-format-wide-pm": "popodne",
	"dateFormat-full": "EEEE, dd. MMMM y.",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMd": "d. M. y.",
	"field-era": "era",
	"dateFormatItem-yM": "y-M",
	"months-standAlone-wide": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"jun",
		"jul",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"timeFormat-short": "HH.mm",
	"quarters-format-wide": [
		"Prvo tromesečje",
		"Drugo tromesečje",
		"Treće tromesečje",
		"Četvrto tromesečje"
	],
	"dateFormatItem-yQQQQ": "QQQQ. y",
	"timeFormat-long": "HH.mm.ss z",
	"field-year": "godina",
	"dateFormatItem-yMMM": "MMM y.",
	"field-hour": "čas",
	"dateFormatItem-MMdd": "MM-dd",
	"months-format-abbr": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"jun",
		"jul",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"timeFormat-full": "HH.mm.ss zzzz",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"months-standAlone-abbr": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"jun",
		"jul",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"quarters-format-abbr": [
		"Prvo tromesečje",
		"Drugo tromesečje",
		"Treće tromesečje",
		"Četvrto tromesečje"
	],
	"quarters-standAlone-wide": [
		"Prvo tromesečje",
		"Drugo tromesečje",
		"Treće tromesečje",
		"Četvrto tromesečje"
	],
	"days-standAlone-wide": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"dateFormatItem-MMMMd": "d. MMMM",
	"timeFormat-medium": "HH.mm.ss",
	"dateFormatItem-yMMdd": "dd.MM.y",
	"dateFormatItem-Hm": "HH.mm",
	"quarters-standAlone-abbr": [
		"Prvo tromesečje",
		"Drugo tromesečje",
		"Treće tromesečje",
		"Četvrto tromesečje"
	],
	"eraAbbr": [
		"p. n. e.",
		"n. e."
	],
	"field-minute": "minut",
	"field-dayperiod": "pre podne/popodne",
	"days-standAlone-abbr": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"dateFormatItem-ms": "mm.ss",
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-day-relative+-1": "juče",
	"dateFormatItem-h": "hh a",
	"field-day-relative+-2": "prekjuče",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-yMMMM": "MMMM y.",
	"field-day": "dan",
	"days-format-wide": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"field-zone": "zona",
	"dateFormatItem-y": "y.",
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"field-year-relative+-1": "Prošle godine",
	"field-month-relative+-1": "Prošlog meseca",
	"dateFormatItem-hm": "hh.mm a",
	"days-format-abbr": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"dateFormatItem-yMMMd": "d. MMM y.",
	"eraNames": [
		"p. n. e.",
		"n. e."
	],
	"days-format-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"field-month": "mesec",
	"days-standAlone-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"dayPeriods-format-wide-am": "pre podne",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormat-short": "d.M.yy.",
	"field-second": "sekund",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"field-month-relative+0": "Ovog meseca",
	"field-month-relative+1": "Sledećeg meseca",
	"dateFormatItem-Ed": "E d.",
	"field-week": "nedelja",
	"dateFormat-medium": "dd.MM.y.",
	"field-year-relative+0": "Ove godine",
	"field-week-relative+-1": "Prošle nedelje",
	"field-year-relative+1": "Sledeće godine",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-hms": "hh.mm.ss a",
	"field-week-relative+0": "Ove nedelje",
	"field-week-relative+1": "Sledeće nedelje"
}
//end v1.x content
);