define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "AM/PM",
	"field-minute": "Minuut",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Gister",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Die dag voor gister",
	"field-weekday": "Weeksdag",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Era",
	"field-hour": "Uur",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Vandag",
	"field-day-relative+1": "Môre",
	"field-day-relative+2": "Die dag na môre",
	"dateFormat-long": "dd MMMM y G",
	"field-zone": "Tydsone",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Verlede week",
	"dateFormat-medium": "dd MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Hierdie jaar",
	"field-year-relative+1": "Volgende jaar",
	"dateFormatItem-yMd": "M/d/y",
	"field-year-relative+-1": "Verlede jaar",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Jaar",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Week",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "Vandeesweek",
	"field-week-relative+1": "Volgende week",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Vandeesmaand",
	"dateFormatItem-H": "HH",
	"field-month": "Maand",
	"field-month-relative+1": "Volgende maand",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Sekonde",
	"field-day": "Dag",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE dd MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Verlede maand",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);