define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM Gy",
	"field-dayperiod": "समय अवधि",
	"field-minute": "मिनट",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-yyyyMMdd": "dd-MM-y G",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "बीता कल",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+-2": "बीता परसों",
	"field-weekday": "सप्ताह का दिन",
	"dateFormatItem-MMM": "MMM",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "Gy",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "युग",
	"field-hour": "घंटा",
	"dateFormatItem-y": "Gy",
	"dateFormatItem-yyyy": "Gy",
	"dateFormatItem-Ed": "d E",
	"field-day-relative+0": "आज",
	"field-day-relative+1": "कल",
	"field-day-relative+2": "परसों",
	"dateFormatItem-GyMMMd": "d MMM Gy",
	"dateFormat-long": "d MMMM Gy",
	"field-zone": "क्षेत्र",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "पिछले सप्ताह",
	"dateFormat-medium": "dd-MM-y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "इस वर्ष",
	"field-year-relative+1": "अगले वर्ष",
	"field-year-relative+-1": "पिछले वर्ष",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ Gy",
	"field-year": "वर्ष",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "सप्ताह",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMMMd": "d MMM Gy",
	"dateFormatItem-yyyyMEd": "E, d/M/y G",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "इस सप्ताह",
	"field-week-relative+1": "अगले सप्ताह",
	"field-month-relative+0": "इस माह",
	"dateFormatItem-H": "HH",
	"field-month": "मास",
	"field-month-relative+1": "अगले माह",
	"dateFormatItem-M": "L",
	"field-second": "सेकेंड",
	"dateFormatItem-GyMMMEd": "E, d MMM Gy",
	"dateFormatItem-GyMMM": "MMM Gy",
	"field-day": "दिन",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-yyyyQQQ": "QQQ Gy",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d-M-y G",
	"dateFormatItem-yyyyM": "M-y G",
	"dateFormat-full": "EEEE, d MMMM Gy",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyMMM": "MMM Gy",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "पिछला माह",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);