define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "AM//PM",
	"field-minute": "Minutuak",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Atzo",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Herenegun",
	"field-weekday": "Asteguna",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "Aroa",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "Ordua",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Gaur",
	"field-day-relative+1": "Bihar",
	"field-day-relative+2": "Etzi",
	"dateFormat-long": "G y MMMM d",
	"field-zone": "Ordu-eremua",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Aurreko astea",
	"dateFormat-medium": "G y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Aurten",
	"field-year-relative+1": "Hurrengo urtea",
	"dateFormatItem-yMd": "y-M-d",
	"field-year-relative+-1": "Aurreko urtea",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Urtea",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Astea",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "Aste hau",
	"field-week-relative+1": "Hurrengo astea",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Gauden hilabetea",
	"dateFormatItem-H": "HH",
	"field-month": "Hilabetea",
	"field-month-relative+1": "Hurrengo hilabetea",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d, y",
	"field-second": "Segundoak",
	"field-day": "Eguna",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, G y MMMM dd",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Aurreko hilabetea"
}
//end v1.x content
);