define(
//begin v1.x content
{
	"field-second": "Giây",
	"field-year-relative+-1": "Năm ngoái",
	"field-week": "Tuần",
	"field-month-relative+-1": "Tháng trước",
	"field-day-relative+-1": "Ngày hôm qua",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-day-relative+-2": "Ngày hôm kia",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-year": "Năm",
	"field-week-relative+0": "Tuần này",
	"months-standAlone-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-week-relative+1": "Tuần sau",
	"field-minute": "Phút",
	"field-week-relative+-1": "Tuần trước",
	"field-day-relative+0": "Hôm nay",
	"field-hour": "Giờ",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"field-day": "Ngày",
	"field-month-relative+0": "Tháng này",
	"field-month-relative+1": "Tháng sau",
	"field-dayperiod": "SA/CH",
	"field-month": "Tháng",
	"months-format-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-era": "Thời đại",
	"field-year-relative+0": "Năm nay",
	"field-year-relative+1": "Năm sau",
	"months-format-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-weekday": "Ngày trong tuần",
	"field-zone": "Múi giờ"
}
//end v1.x content
);