define(
//begin v1.x content
{
	"days-standAlone-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-weekday": "Ngày trong tuần",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, dd-M-y",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"eraNarrow": [
		"tr. CN",
		"sau CN"
	],
	"dateFormatItem-yMM": "MM-y",
	"days-format-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y",
	"months-format-wide": [
		"tháng một",
		"tháng hai",
		"tháng ba",
		"tháng tư",
		"tháng năm",
		"tháng sáu",
		"tháng bảy",
		"tháng tám",
		"tháng chín",
		"tháng mười",
		"tháng mười một",
		"tháng mười hai"
	],
	"dateTimeFormat-medium": "{0} {1}",
	"dayPeriods-format-wide-pm": "CH",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y",
	"dateFormatItem-Md": "dd-M",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "Thời đại",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"tháng một",
		"tháng hai",
		"tháng ba",
		"tháng tư",
		"tháng năm",
		"tháng sáu",
		"tháng bảy",
		"tháng tám",
		"tháng chín",
		"tháng mười",
		"tháng mười một",
		"tháng mười hai"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Năm",
	"dateFormatItem-yMMM": "MMM y",
	"field-hour": "Giờ",
	"dateFormatItem-MMdd": "dd-MM",
	"months-format-abbr": [
		"thg 1",
		"thg 2",
		"thg 3",
		"thg 4",
		"thg 5",
		"thg 6",
		"thg 7",
		"thg 8",
		"thg 9",
		"thg 10",
		"thg 11",
		"thg 12"
	],
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"thg 1",
		"thg 2",
		"thg 3",
		"thg 4",
		"thg 5",
		"thg 6",
		"thg 7",
		"thg 8",
		"thg 9",
		"thg 10",
		"thg 11",
		"thg 12"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	],
	"dateFormatItem-MMMMd": "dd MMMM",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"tr. CN",
		"sau CN"
	],
	"field-minute": "Phút",
	"field-dayperiod": "SA/CH",
	"days-standAlone-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"dateFormatItem-d": "'Ngày' dd",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Ngày hôm qua",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{0} {1}",
	"field-day-relative+-2": "Ngày hôm kia",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-MEd": "E, dd-M",
	"dateTimeFormat-full": "{0} {1}",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "Ngày",
	"days-format-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	],
	"field-zone": "Múi giờ",
	"dateFormatItem-y": "'Năm' y",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-year-relative+-1": "Năm ngoái",
	"field-month-relative+-1": "Tháng trước",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"dateFormatItem-yMMMd": "dd MMM, y",
	"eraNames": [
		"tr. CN",
		"sau CN"
	],
	"days-format-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"field-month": "Tháng",
	"days-standAlone-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "SA",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"dateFormat-short": "dd/MM/y",
	"field-second": "Giây",
	"dateFormatItem-yMMMEd": "E, dd MMM y",
	"field-month-relative+0": "Tháng này",
	"field-month-relative+1": "Tháng sau",
	"dateFormatItem-Ed": "E, dd",
	"field-week": "Tuần",
	"dateFormat-medium": "dd-MM-y",
	"field-year-relative+0": "Năm nay",
	"field-week-relative+-1": "Tuần trước",
	"field-year-relative+1": "Năm sau",
	"dateFormatItem-mmss": "mm:ss",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-week-relative+0": "Tuần này",
	"field-week-relative+1": "Tuần sau"
}
//end v1.x content
);