define(
//begin v1.x content
{
	"field-dayperiod": "SA/CH",
	"months-standAlone-abbr-leap": "Adar II",
	"dayPeriods-format-wide-pm": "CH",
	"field-minute": "Phút",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"dateTimeFormat-full": "{0} {1}",
	"field-day-relative+-1": "Ngày hôm qua",
	"field-weekday": "Ngày trong tuần",
	"field-day-relative+-2": "Ngày hôm kia",
	"days-standAlone-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	],
	"dateTimeFormat-short": "{0} {1}",
	"field-era": "Thời đại",
	"field-hour": "Giờ",
	"dayPeriods-format-wide-am": "SA",
	"dateTimeFormat-medium": "{0} {1}",
	"months-format-abbr-leap": "Adar II",
	"dateFormatItem-y": "'Năm' y",
	"months-standAlone-abbr": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"dateFormatItem-Ed": "E, dd",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"days-standAlone-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"field-day-relative+2": "Ngày kia",
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"field-zone": "Múi giờ",
	"dateFormatItem-Hm": "H:mm",
	"field-week-relative+-1": "Tuần trước",
	"dateFormat-medium": "dd-MM-y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"field-year-relative+0": "Năm nay",
	"field-year-relative+1": "Năm sau",
	"quarters-standAlone-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"field-year-relative+-1": "Năm ngoái",
	"field-year": "Năm",
	"dateTimeFormat-long": "{0} {1}",
	"months-standAlone-wide": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"field-week": "Tuần",
	"dateFormatItem-MMMd": "dd MMM",
	"field-week-relative+0": "Tuần này",
	"field-week-relative+1": "Tuần sau",
	"months-format-abbr": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"field-month-relative+0": "Tháng này",
	"field-month": "Tháng",
	"field-month-relative+1": "Tháng sau",
	"days-format-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"days-format-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"field-second": "Giây",
	"field-day": "Ngày",
	"dateFormatItem-MEd": "E, dd-M",
	"days-standAlone-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"months-standAlone-wide-leap": "Adar II",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-Md": "dd-M",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y G",
	"days-format-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormatItem-d": "'Ngày' dd",
	"field-month-relative+-1": "Tháng trước",
	"quarters-format-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"days-format-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	]
}
//end v1.x content
);