define(
//begin v1.x content
{
	"days-standAlone-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"field-weekday": "Ngày trong tuần",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, dd-M-y",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"dateFormatItem-yMM": "MM-y G",
	"days-format-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"dateTimeFormat-medium": "{0} {1}",
	"dayPeriods-format-wide-pm": "CH",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y G",
	"dateFormatItem-Md": "dd-M",
	"dateFormatItem-yMd": "dd-M-y G",
	"field-era": "Thời đại",
	"dateFormatItem-yM": "M/y",
	"quarters-format-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-year": "Năm",
	"dateFormatItem-yMMM": "MMM y",
	"field-hour": "Giờ",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"dateFormatItem-H": "HH",
	"quarters-standAlone-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	],
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-Hm": "HH:mm",
	"field-minute": "Phút",
	"field-dayperiod": "SA/CH",
	"dateFormatItem-d": "'Ngày' dd",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "Ngày hôm qua",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{0} {1}",
	"field-day-relative+-2": "Ngày hôm kia",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-MEd": "E, dd-M",
	"dateTimeFormat-full": "{0} {1}",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "Ngày",
	"days-format-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	],
	"field-zone": "Múi giờ",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "Năm ngoái",
	"field-month-relative+-1": "Tháng trước",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"dateFormatItem-yMMMd": "dd MMM y G",
	"days-format-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"field-month": "Tháng",
	"days-standAlone-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "SA",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"dateFormat-short": "dd/MM/y G",
	"field-second": "Giây",
	"dateFormatItem-yMMMEd": "E, dd MMM y",
	"field-month-relative+0": "Tháng này",
	"field-month-relative+1": "Tháng sau",
	"dateFormatItem-Ed": "E, dd",
	"field-week": "Tuần",
	"dateFormat-medium": "dd-MM-y G",
	"field-year-relative+0": "Năm nay",
	"field-week-relative+-1": "Tuần trước",
	"field-year-relative+1": "Năm sau",
	"dateFormatItem-mmss": "mm:ss",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-week-relative+0": "Tuần này",
	"field-week-relative+1": "Tuần sau"
}
//end v1.x content
);