define(
//begin v1.x content
{
	"field-dayperiod": "SA/CH",
	"field-minute": "Phút",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"field-day-relative+-1": "Ngày hôm qua",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+-2": "Ngày hôm kia",
	"field-weekday": "Ngày trong tuần",
	"field-era": "Thời đại",
	"field-hour": "Giờ",
	"dateFormatItem-y": "'Năm' y G",
	"dateFormatItem-yMM": "MM-y G",
	"dateFormatItem-Ed": "E, dd",
	"dateFormatItem-yMMM": "MMM y G",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"field-zone": "Múi giờ",
	"field-week-relative+-1": "Tuần trước",
	"dateFormat-medium": "dd-MM-y G",
	"field-year-relative+0": "Năm nay",
	"field-year-relative+1": "Năm sau",
	"dateFormatItem-yMd": "dd-M-y G",
	"field-year-relative+-1": "Năm ngoái",
	"dateFormatItem-yMMMM": "MMMM y G",
	"field-year": "Năm",
	"field-week": "Tuần",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"dateFormatItem-MMMd": "dd MMM",
	"field-week-relative+0": "Tuần này",
	"field-week-relative+1": "Tuần sau",
	"dateFormatItem-yQQQQ": "QQQQ y G",
	"field-month-relative+0": "Tháng này",
	"field-month": "Tháng",
	"field-month-relative+1": "Tháng sau",
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-yMMMd": "dd MMM y G",
	"field-second": "Giây",
	"field-day": "Ngày",
	"dateFormatItem-MEd": "E, dd-M",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-yMMMEd": "E, dd MMM y G",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y G",
	"dateFormatItem-Md": "dd-M",
	"dateFormatItem-yMEd": "E, dd-M-y G",
	"dateFormatItem-d": "'Ngày' dd",
	"field-month-relative+-1": "Tháng trước"
}
//end v1.x content
);