define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "претпладне/попладне",
	"field-minute": "Минута",
	"dateFormatItem-MMMEd": "E MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Вчера",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "завчера",
	"field-weekday": "Ден во неделата",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Ера",
	"field-hour": "Час",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "Денес",
	"field-day-relative+1": "Утре",
	"field-day-relative+2": "задутре",
	"dateFormat-long": "dd MMMM y G",
	"field-zone": "зона",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd.M.y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d-M-y",
	"dateFormatItem-yMMMM": "y MMMM",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "година",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Недела",
	"dateFormatItem-MMMMEd": "E MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"dateFormatItem-H": "HH",
	"field-month": "Месец",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "Секунда",
	"field-day": "ден",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.M.yy GGGGG",
	"dateFormatItem-Mdd": "dd.M",
	"dateFormatItem-yMMMEd": "E, y MMM d",
	"dateFormat-full": "EEEE, dd MMMM y G",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);