define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "ŋkekea me",
	"field-minute": "Mintigaƒoƒo",
	"dateFormatItem-MMMEd": "E, MMM d 'lia'",
	"dateTimeFormat-full": "{0} {1}",
	"field-day-relative+-1": "etsɔ si va yi",
	"dateFormatItem-hms": "a 'ga' h:mm:ss",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "nyitsɔ",
	"field-weekday": "kɔsiɖa me ŋkeke",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{0} {1}",
	"dateTimeFormat-medium": "{0} {1}",
	"field-era": "ŋɔli",
	"field-hour": "gaƒoƒo",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "egbe",
	"field-day-relative+1": "etsɔ si gbɔna",
	"field-day-relative+2": "nyitsɔ si gbɔna",
	"dateFormat-long": "MMMM d 'lia' y G",
	"field-zone": "nutomegaƒoƒome",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "MMM d 'lia', y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "M/d/y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "'aɖabaƒoƒo' mm:ss",
	"field-year": "ƒe",
	"dateTimeFormat-long": "{0} {1}",
	"field-week": "kɔsiɖa ɖeka",
	"dateFormatItem-MMMMEd": "E, MMMM d 'lia'",
	"dateFormatItem-MMMd": "MMM d 'lia'",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-H": "HH",
	"field-month": "Xleti",
	"dateFormatItem-MMMMd": "MMMM d 'lia'",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d 'lia', y",
	"field-second": "sekend",
	"field-day": "ŋkeke",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "a 'ga' h:mm",
	"dateFormat-short": "M/d/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, MMMM d 'lia' y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "a 'ga' h"
}
//end v1.x content
);