define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.y 'г'.",
	"field-dayperiod": "ден",
	"field-minute": "минута",
	"dateFormatItem-MMMEd": "d MMM, E",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "Вчера",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd.MM",
	"dateFormatItem-yQQQ": "QQQ y 'г'.",
	"field-day-relative+-2": "Онзи ден",
	"field-weekday": "Ден от седмицата",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-era": "ера",
	"field-hour": "час",
	"dateFormatItem-y": "y 'г'.",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "MMM y 'г'.",
	"field-day-relative+0": "Днес",
	"field-day-relative+1": "Утре",
	"field-day-relative+2": "Вдругиден",
	"dateFormat-long": "dd MMMM y G",
	"field-zone": "зона",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Миналата седмица",
	"dateFormat-medium": "dd.MM.y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Тази година",
	"field-year-relative+1": "Следващата година",
	"dateFormatItem-yMd": "dd.MM.y",
	"field-year-relative+-1": "Миналата година",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "година",
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "седмица",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Тази седмица",
	"field-week-relative+1": "Следващата седмица",
	"dateFormatItem-yQQQQ": "QQQQ y 'г'.",
	"field-month-relative+0": "Този месец",
	"dateFormatItem-H": "HH",
	"field-month": "месец",
	"field-month-relative+1": "Следващия месец",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "dd MMM y",
	"field-second": "секунда",
	"field-day": "Ден",
	"dateFormatItem-MEd": "E, d.MM",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM y 'г'.",
	"dateFormat-full": "dd MMMM y G, EEEE",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "E, d.MM.y 'г'.",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Миналия месец",
	"dateFormatItem-h": "h"
}
//end v1.x content
);