define(
//begin v1.x content
{
	"field-dayperiod": "ден",
	"dayPeriods-format-wide-pm": "сл. об.",
	"field-minute": "минута",
	"dateFormatItem-MMMEd": "d MMM, E",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "Вчера",
	"field-weekday": "Ден от седмицата",
	"field-day-relative+-2": "Онзи ден",
	"dateTimeFormat-short": "{1}, {0}",
	"field-era": "ера",
	"field-hour": "час",
	"dayPeriods-format-wide-am": "пр. об.",
	"dateTimeFormat-medium": "{1}, {0}",
	"quarters-standAlone-abbr": [
		"1 трим.",
		"2 трим.",
		"3 трим.",
		"4 трим."
	],
	"dateFormatItem-y": "y 'г'.",
	"months-standAlone-abbr": [
		"мухарам",
		"сафар",
		"раби-1",
		"раби-2",
		"джумада-1",
		"джумада-2",
		"раджаб",
		"шабан",
		"рамазан",
		"Шавал",
		"Дхул-Каада",
		"Дхул-хиджа"
	],
	"dateFormatItem-Ed": "E, d",
	"field-day-relative+0": "Днес",
	"field-day-relative+1": "Утре",
	"days-standAlone-narrow": [
		"н",
		"п",
		"в",
		"с",
		"ч",
		"п",
		"с"
	],
	"field-day-relative+2": "Вдругиден",
	"dateFormat-long": "dd MMMM y G",
	"field-zone": "зона",
	"field-week-relative+-1": "Миналата седмица",
	"dateFormat-medium": "dd.MM.y G",
	"field-year-relative+0": "Тази година",
	"field-year-relative+1": "Следващата година",
	"field-year-relative+-1": "Миналата година",
	"field-year": "година",
	"dateTimeFormat-long": "{1}, {0}",
	"months-standAlone-wide": [
		"мухарам",
		"сафар",
		"раби-1",
		"раби-2",
		"джумада-1",
		"джумада-2",
		"раджаб",
		"шабан",
		"рамазан",
		"Шавал",
		"Дхул-Каада",
		"Дхул-хиджа"
	],
	"field-week": "седмица",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Тази седмица",
	"field-week-relative+1": "Следващата седмица",
	"months-format-abbr": [
		"мухарам",
		"сафар",
		"раби-1",
		"раби-2",
		"джумада-1",
		"джумада-2",
		"раджаб",
		"шабан",
		"рамазан",
		"Шавал",
		"Дхул-Каада",
		"Дхул-хиджа"
	],
	"field-month-relative+0": "Този месец",
	"field-month": "месец",
	"field-month-relative+1": "Следващия месец",
	"quarters-format-abbr": [
		"I трим.",
		"II трим.",
		"III трим.",
		"IV трим."
	],
	"days-format-abbr": [
		"нд",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"field-second": "секунда",
	"field-day": "Ден",
	"dateFormatItem-MEd": "E, d.MM",
	"days-standAlone-short": [
		"нд",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormat-full": "dd MMMM y G, EEEE",
	"dateFormatItem-Md": "d.M",
	"months-format-wide": [
		"мухарам",
		"сафар",
		"раби-1",
		"раби-2",
		"джумада-1",
		"джумада-2",
		"раджаб",
		"шабан",
		"рамазан",
		"Шавал",
		"Дхул-Каада",
		"Дхул-хиджа"
	],
	"days-format-short": [
		"нд",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"field-month-relative+-1": "Миналия месец",
	"quarters-format-wide": [
		"1-во тримесечие",
		"2-ро тримесечие",
		"3-то тримесечие",
		"4-то тримесечие"
	],
	"days-format-wide": [
		"неделя",
		"понеделник",
		"вторник",
		"сряда",
		"четвъртък",
		"петък",
		"събота"
	],
	"dateFormatItem-h": "h"
}
//end v1.x content
);