define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d. MMM y. G",
	"field-dayperiod": "dio dana",
	"field-minute": "minuta",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "jučer",
	"dateFormatItem-hms": "hh:mm:ss a",
	"field-day-relative+-2": "prekjučer",
	"field-weekday": "dan u tjednu",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y. G",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "era",
	"field-hour": "sat",
	"dateFormatItem-y": "y. G",
	"dateFormatItem-yyyy": "y. G",
	"dateFormatItem-Ed": "E, d.",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"dateFormatItem-GyMMMd": "d. MMM y. G",
	"dateFormatItem-yyyyMMMM": "LLLL y. G",
	"dateFormat-long": "d. MMMM y. G",
	"field-zone": "vremenska zona",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Prošli tjedan",
	"dateFormat-medium": "d. M. y. G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Ova godina",
	"field-year-relative+1": "Sljedeća godina",
	"field-year-relative+-1": "Prošla godina",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y. G",
	"field-year": "godina",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "tjedan",
	"dateFormatItem-yyyyMd": "d. M. y. G",
	"dateFormatItem-yyyyMMMd": "d. MMM y. G",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-yyyyMEd": "E, d. M. y. G",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "Ovaj tjedan",
	"field-week-relative+1": "Sljedeći tjedan",
	"field-month-relative+0": "Ovaj mjesec",
	"dateFormatItem-H": "HH",
	"field-month": "mjesec",
	"field-month-relative+1": "Sljedeći mjesec",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormatItem-M": "L.",
	"field-second": "sekunda",
	"dateFormatItem-GyMMMEd": "E, d. MMM y. G",
	"dateFormatItem-GyMMM": "LLL y. G",
	"field-day": "dan",
	"dateFormatItem-MEd": "E, d. M.",
	"dateFormatItem-yyyyQQQ": "QQQ y. G",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "d.M.y. GGGGG",
	"dateFormatItem-yyyyM": "M. y. G",
	"dateFormat-full": "EEEE, d. MMMM y. G",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-yyyyMMM": "LLL y. G",
	"dateFormatItem-d": "d.",
	"field-month-relative+-1": "Prošli mjesec",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);