define(
//begin v1.x content
{
	"dateFormatItem-yM": "M. y. GGGGG",
	"field-dayperiod": "dio dana",
	"field-minute": "minuta",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"field-day-relative+-1": "jučer",
	"field-weekday": "dan u tjednu",
	"dateFormatItem-yQQQ": "QQQ y. GGGGG",
	"field-day-relative+-2": "prekjučer",
	"field-era": "era",
	"dateFormatItem-Gy": "y. GGG",
	"field-hour": "sat",
	"dateFormatItem-y": "y. GGG",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-yMMM": "LLL y. GGGGG",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"field-zone": "vremenska zona",
	"field-week-relative+-1": "Prošli tjedan",
	"field-year-relative+0": "Ova godina",
	"field-year-relative+1": "Sljedeća godina",
	"dateFormatItem-yMd": "d. M. y. GGGGG",
	"field-year-relative+-1": "Prošla godina",
	"field-year": "godina",
	"field-week": "tjedan",
	"field-week-relative+0": "Ovaj tjedan",
	"field-week-relative+1": "Sljedeći tjedan",
	"field-month-relative+0": "Ovaj mjesec",
	"field-month": "mjesec",
	"field-month-relative+1": "Sljedeći mjesec",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-yMMMd": "d. MMM y. GGGGG",
	"field-second": "sekunda",
	"field-day": "dan",
	"dateFormatItem-MEd": "E, d. M.",
	"dateFormatItem-yMMMEd": "E, d. MMM y. GGGGG",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-yMEd": "E, d. M. y. GGGGG",
	"field-month-relative+-1": "Prošli mjesec"
}
//end v1.x content
);