define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"field-dayperiod": "قبل/بعدازظهر",
	"field-minute": "دقیقه",
	"dateFormatItem-MMMEd": "E d LLL",
	"dateTimeFormat-full": "{1}، ساعت {0}",
	"field-day-relative+-1": "دیروز",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-day-relative+-2": "پریروز",
	"field-weekday": "روز هفته",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}،‏ {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1}،‏ {0}",
	"field-era": "دوره",
	"field-hour": "ساعت",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d",
	"field-day-relative+0": "امروز",
	"field-day-relative+1": "فردا",
	"field-day-relative+2": "پسفردا",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "منطقهٔ زمانی",
	"dateFormatItem-Hm": "H:mm",
	"field-week-relative+-1": "هفتهٔ گذشته",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-HHmmZ": "HH:mm (Z)",
	"field-year-relative+0": "امسال",
	"field-year-relative+1": "سال آینده",
	"field-year-relative+-1": "سال گذشته",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-year": "سال",
	"dateTimeFormat-long": "{1}، ساعت {0}",
	"field-week": "هفته",
	"dateFormatItem-yyyyMd": "y/M/d G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMEd": "E d LLLL",
	"dateFormatItem-yyyyMEd": "E y/M/d G",
	"dateFormatItem-MMMd": "d LLL",
	"field-week-relative+0": "این هفته",
	"field-week-relative+1": "هفتهٔ آینده",
	"field-month-relative+0": "این ماه",
	"dateFormatItem-H": "H",
	"field-month": "ماه",
	"field-month-relative+1": "ماه آینده",
	"dateFormatItem-MMMMd": "d LLLL",
	"dateFormatItem-M": "L",
	"field-second": "ثانیه",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-day": "روز",
	"dateFormatItem-MEd": "E M/d",
	"dateFormatItem-yyyyQQQ": "QQQQ y G",
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "y/M/d G",
	"dateFormatItem-yyyyM": "y/M G",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "ماه گذشته",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);