define(
//begin v1.x content
{
	"days-standAlone-short": [
		"۱ش",
		"۲ش",
		"۳ش",
		"۴ش",
		"۵ش",
		"ج",
		"ش"
	],
	"months-format-narrow": [
		"م",
		"ص",
		"ر",
		"ر",
		"ج",
		"ج",
		"ر",
		"ش",
		"ر",
		"ش",
		"ذ",
		"ذ"
	],
	"quarters-standAlone-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"field-weekday": "روز هفته",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E y/M/d",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d LLL",
	"eraNarrow": [
		"ه.ق."
	],
	"days-format-short": [
		"۱ش",
		"۲ش",
		"۳ش",
		"۴ش",
		"۵ش",
		"ج",
		"ش"
	],
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}",
	"dateFormat-long": "d MMMM y G",
	"months-format-wide": [
		"محرم",
		"صفر",
		"ربیع الاول",
		"ربیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذیقعدهٔ",
		"ذیحجهٔ"
	],
	"dateFormatItem-yyyyQQQ": "QQQQ y G",
	"dateTimeFormat-medium": "{1}، {0}",
	"dayPeriods-format-wide-pm": "بعدازظهر",
	"dateFormat-full": "EEEE d MMMM y GGGG",
	"dateFormatItem-yyyyMEd": "E y/M/d G",
	"dateFormatItem-Md": "M/d",
	"field-era": "دوره",
	"dateFormatItem-yM": "y/M",
	"months-standAlone-wide": [
		"محرم",
		"صفر",
		"ربیع الاول",
		"ربیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذیقعده",
		"ذیحجه"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"timeFormat-long": "H:mm:ss (z)",
	"field-year": "سال",
	"dateFormatItem-yMMM": "MMM y",
	"field-hour": "ساعت",
	"months-format-abbr": [
		"محرم",
		"صفر",
		"ربیع الاول",
		"ربیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذیقعدهٔ",
		"ذیحجهٔ"
	],
	"timeFormat-full": "H:mm:ss (zzzz)",
	"field-day-relative+0": "امروز",
	"field-day-relative+1": "فردا",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-day-relative+2": "پسفردا",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"محرم",
		"صفر",
		"ربیع الاول",
		"ربیع الثانی",
		"جمادی الاول",
		"جمادی الثانی",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذیقعده",
		"ذیحجه"
	],
	"quarters-format-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"quarters-standAlone-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMd": "d LLLL",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"eraAbbr": [
		"ه.ق."
	],
	"field-minute": "دقیقه",
	"field-dayperiod": "قبل/بعدازظهر",
	"days-standAlone-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"field-day-relative+-1": "دیروز",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1}، ساعت {0}",
	"field-day-relative+-2": "پریروز",
	"dateFormatItem-MMMd": "d LLL",
	"dateFormatItem-MEd": "E M/d",
	"dateTimeFormat-full": "{1}، ساعت {0}",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "روز",
	"days-format-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"field-zone": "منطقهٔ زمانی",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"م",
		"ص",
		"ر",
		"ر",
		"ج",
		"ج",
		"ر",
		"ش",
		"ر",
		"ش",
		"ذ",
		"ذ"
	],
	"field-year-relative+-1": "سال گذشته",
	"field-month-relative+-1": "ماه گذشته",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"eraNames": [
		"هجری قمری"
	],
	"days-format-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dateFormatItem-yyyyMd": "y/M/d G",
	"field-month": "ماه",
	"dateFormatItem-MMM": "LLL",
	"days-standAlone-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dayPeriods-format-wide-am": "قبلازظهر",
	"dateFormatItem-MMMMEd": "E d LLLL",
	"dateFormat-short": "yy/M/d G",
	"field-second": "ثانیه",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"field-month-relative+0": "این ماه",
	"field-month-relative+1": "ماه آینده",
	"dateFormatItem-Ed": "E d",
	"field-week": "هفته",
	"dateFormat-medium": "y/M/d G",
	"field-year-relative+0": "امسال",
	"field-week-relative+-1": "هفتهٔ گذشته",
	"dateFormatItem-yyyyM": "y/M G",
	"field-year-relative+1": "سال آینده",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1}، {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "این هفته",
	"field-week-relative+1": "هفتهٔ آینده"
}
//end v1.x content
);