define(
//begin v1.x content
{
	"dateFormatItem-yM": "M-y",
	"field-dayperiod": "ព្រឹក/ល្ងាច",
	"field-minute": "នាទី",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "ម្សិលមិញ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "ម្សិលម៉្ងៃ",
	"field-weekday": "ថ្ងៃនៃសប្ដាហ៍",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"field-era": "សករាជ",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-hour": "ម៉ោង",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ថ្ងៃនេះ",
	"field-day-relative+1": "ថ្ងៃស្អែក",
	"field-day-relative+2": "ខានស្អែក",
	"dateFormat-long": "d MMMM, y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d-M-y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ឆ្នាំ",
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "សប្ដាហ៍",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "ខែ",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "វិនាទី",
	"field-day": "ថ្ងៃ",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, d-M-y",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);