define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "දිවා කාලය",
	"field-minute": "මිනිස්තුව",
	"dateFormatItem-MMMEd": "MMM d E",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ඊයෙ",
	"dateFormatItem-hms": "a h.mm.ss",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "පෙරේදා",
	"field-weekday": "සතියේ දිනය",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "යුගය",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "පැය",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "අද",
	"field-day-relative+1": "හෙට",
	"field-day-relative+2": "අනිද්දා",
	"dateFormat-long": "G y MMMM d",
	"field-zone": "වේලා කලාපය",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "G y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "y-M-d",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "වර්ෂ",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "සතිය",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "මාසය",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "තප්පරය",
	"field-day": "දිනය",
	"dateFormatItem-MEd": "M-d, E",
	"dateFormatItem-hm": "a h.mm",
	"dateFormat-short": "GGGGG y/MM/dd",
	"dateFormatItem-yMMMEd": "y MMM d, E",
	"dateFormat-full": "G y MMMM d, EEEE",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "y-M-d, E",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "a h"
}
//end v1.x content
);