define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y G",
	"field-dayperiod": "PG/PTG",
	"dayPeriods-format-wide-pm": "PTG",
	"field-minute": "Minit",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "Semalam",
	"field-weekday": "Hari dalam Minggu",
	"field-day-relative+-2": "Hari sebelum semalam",
	"days-standAlone-wide": [
		"Ahad",
		"Isnin",
		"Selasa",
		"Rabu",
		"Khamis",
		"Jumaat",
		"Sabtu"
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"O",
		"S",
		"O",
		"N",
		"D"
	],
	"field-era": "Era",
	"field-hour": "Jam",
	"dayPeriods-format-wide-am": "PG",
	"quarters-standAlone-abbr": [
		"Suku 1",
		"Suku Ke-2",
		"Suku Ke-3",
		"Suku Ke-4"
	],
	"dateFormatItem-y": "y",
	"timeFormat-full": "h:mm:ss a zzzz",
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mac",
		"Apr",
		"Mei",
		"Jun",
		"Jul",
		"Ogos",
		"Sep",
		"Okt",
		"Nov",
		"Dis"
	],
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "MMM y G",
	"field-day-relative+0": "Hari ini",
	"field-day-relative+1": "Esok",
	"days-standAlone-narrow": [
		"A",
		"I",
		"S",
		"R",
		"K",
		"J",
		"S"
	],
	"field-day-relative+2": "Hari selepas esok",
	"dateFormat-long": "d MMMM y G",
	"timeFormat-medium": "h:mm:ss a",
	"field-zone": "Zon Waktu",
	"field-week-relative+-1": "Minggu lepas",
	"dateFormat-medium": "dd/MM/y G",
	"field-year-relative+0": "Tahun ini",
	"field-year-relative+1": "Tahun depan",
	"quarters-standAlone-wide": [
		"Suku pertama",
		"Suku Ke-2",
		"Suku Ke-3",
		"Suku Ke-4"
	],
	"field-year-relative+-1": "Tahun lepas",
	"field-year": "Tahun",
	"months-standAlone-wide": [
		"Januari",
		"Februari",
		"Mac",
		"April",
		"Mei",
		"Jun",
		"Julai",
		"Ogos",
		"September",
		"Oktober",
		"November",
		"Disember"
	],
	"field-week": "Minggu",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Minggu ini",
	"field-week-relative+1": "Minggu seterusnya",
	"timeFormat-long": "h:mm:ss a z",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mac",
		"Apr",
		"Mei",
		"Jun",
		"Jul",
		"Ogos",
		"Sep",
		"Okt",
		"Nov",
		"Dis"
	],
	"field-month-relative+0": "Bulan ini",
	"field-month": "Bulan",
	"field-month-relative+1": "Bulan seterusnya",
	"timeFormat-short": "h:mm a",
	"dateFormatItem-MMMMd": "d MMMM",
	"quarters-format-abbr": [
		"Suku 1",
		"Suku Ke-2",
		"Suku Ke-3",
		"Suku Ke-4"
	],
	"days-format-abbr": [
		"Ahd",
		"Isn",
		"Sel",
		"Rab",
		"Kha",
		"Jum",
		"Sab"
	],
	"days-format-narrow": [
		"A",
		"I",
		"S",
		"R",
		"K",
		"J",
		"S"
	],
	"dateFormatItem-yMMMd": "d MMM y G",
	"field-second": "Kedua",
	"field-day": "Hari",
	"dateFormatItem-MEd": "E, d/M",
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"O",
		"S",
		"O",
		"N",
		"D"
	],
	"days-standAlone-short": [
		"Ah",
		"Is",
		"Se",
		"Ra",
		"Kh",
		"Ju",
		"Sa"
	],
	"days-standAlone-abbr": [
		"Ahd",
		"Isn",
		"Sel",
		"Rab",
		"Kha",
		"Jum",
		"Sab"
	],
	"dayPeriods-format-abbr-pm": "ptg",
	"dateFormat-short": "d/MM/y G",
	"dateFormatItem-yMMMEd": "E, d MMM y G",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y G",
	"months-format-wide": [
		"Januari",
		"Februari",
		"Mac",
		"April",
		"Mei",
		"Jun",
		"Julai",
		"Ogos",
		"September",
		"Oktober",
		"November",
		"Disember"
	],
	"dayPeriods-format-abbr-am": "pg",
	"days-format-short": [
		"Ah",
		"Is",
		"Se",
		"Ra",
		"Kh",
		"Ju",
		"Sa"
	],
	"field-month-relative+-1": "Bulan lalu",
	"quarters-format-wide": [
		"Suku pertama",
		"Suku Ke-2",
		"Suku Ke-3",
		"Suku Ke-4"
	],
	"days-format-wide": [
		"Ahad",
		"Isnin",
		"Selasa",
		"Rabu",
		"Khamis",
		"Jumaat",
		"Sabtu"
	]
}
//end v1.x content
);