define(
//begin v1.x content
{
	"dateFormat-medium": "U MMM d",
	"field-second": "Kedua",
	"field-year-relative+-1": "Tahun lepas",
	"field-week": "Minggu",
	"field-month-relative+-1": "Bulan lalu",
	"field-day-relative+-1": "Semalam",
	"months-format-narrow": [
		"Jn",
		"Fb",
		"Mc",
		"Ap",
		"Me",
		"Ju",
		"Jl",
		"Og",
		"Sp",
		"Ok",
		"Nv",
		"Ds"
	],
	"field-day-relative+-2": "Hari sebelum semalam",
	"months-standAlone-narrow": [
		"Jn",
		"Fe",
		"Mc",
		"Ap",
		"Me",
		"Ju",
		"Jl",
		"Og",
		"Sp",
		"Ok",
		"Nv",
		"Ds"
	],
	"months-standAlone-wide": [
		"Januari",
		"Februari",
		"Mac",
		"April",
		"Mei",
		"Jun",
		"Julai",
		"Ogos",
		"September",
		"Oktober",
		"November",
		"Disember"
	],
	"field-year": "Tahun",
	"field-week-relative+0": "Minggu ini",
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mac",
		"Apr",
		"Mei",
		"Jun",
		"Jul",
		"Ogo",
		"Sep",
		"Okt",
		"Nov",
		"Dis"
	],
	"field-week-relative+1": "Minggu seterusnya",
	"field-minute": "Minit",
	"field-week-relative+-1": "Minggu lepas",
	"field-day-relative+0": "Hari ini",
	"field-hour": "Jam",
	"field-day-relative+1": "Esok",
	"dateFormat-long": "U MMMM d",
	"field-day-relative+2": "Hari selepas esok",
	"field-day": "Hari",
	"field-month-relative+0": "Bulan ini",
	"field-month-relative+1": "Bulan seterusnya",
	"field-dayperiod": "PG/PTG",
	"field-month": "Bulan",
	"dateFormat-short": "y-M-d",
	"months-format-wide": [
		"Januari",
		"Februari",
		"Mac",
		"April",
		"Mei",
		"Jun",
		"Julai",
		"Ogos",
		"September",
		"Oktober",
		"November",
		"Disember"
	],
	"field-era": "Era",
	"field-year-relative+0": "Tahun ini",
	"field-year-relative+1": "Tahun depan",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mac",
		"Apr",
		"Mei",
		"Jun",
		"Jul",
		"Ogo",
		"Sep",
		"Okt",
		"Nov",
		"Dis"
	],
	"dateFormat-full": "EEEE, U MMMM dd",
	"field-weekday": "Hari dalam Minggu",
	"field-zone": "Zon Waktu"
}
//end v1.x content
);