define(
//begin v1.x content
{
	"dateFormatItem-yM": "M-y",
	"field-dayperiod": "PG/PTG",
	"field-minute": "Minit",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Semalam",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"field-day-relative+-2": "Hari sebelum semalam",
	"field-weekday": "Hari dalam Minggu",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Era",
	"field-hour": "Jam",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Hari ini",
	"field-day-relative+1": "Esok",
	"field-day-relative+2": "Hari selepas esok",
	"dateFormatItem-Hmm": "H:mm",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Zon Waktu",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Minggu lepas",
	"dateFormat-medium": "dd/MM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Tahun ini",
	"field-year-relative+1": "Tahun depan",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "Tahun lepas",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Tahun",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Minggu",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "Minggu ini",
	"field-week-relative+1": "Minggu seterusnya",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "Bulan ini",
	"dateFormatItem-H": "HH",
	"field-month": "Bulan",
	"field-month-relative+1": "Bulan seterusnya",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Kedua",
	"field-day": "Hari",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/MM/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Bulan lalu",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);