define(
//begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"field-minute": "မိနစ်",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "မနေ့က",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "တနေ့က",
	"field-weekday": "နေ့",
	"dateFormatItem-MMM": "LLL",
	"field-era": "ခေတ်",
	"field-hour": "နာရီ",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "ယနေ့",
	"field-day-relative+1": "မနက်ဖြန်",
	"field-day-relative+2": "သဘက်ခါ",
	"dateFormat-long": "G y MMMM d",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "G y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "y MMMM",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "နှစ်",
	"field-week": "ပတ်",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "လ",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "စက္ကန့်",
	"field-day": "ရက်",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormat-short": "GGGGG yy/MM/dd",
	"dateFormatItem-yMMMEd": "E, y MMM d",
	"dateFormat-full": "EEEE, G y MMMM dd",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, y/M/d",
	"dateFormatItem-d": "d"
}
//end v1.x content
);