define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.y",
	"field-dayperiod": "enne/pärast lõunat",
	"field-minute": "minut",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "eile",
	"dateFormatItem-hms": "h:mm.ss a",
	"dateFormatItem-MMdd": "dd.MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "üleeile",
	"field-weekday": "nädalapäev",
	"dateFormatItem-MMM": "MMMM",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "ajastu",
	"field-hour": "tund",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "täna",
	"field-day-relative+1": "homme",
	"field-day-relative+2": "ülehomme",
	"dateFormat-long": "d. MMMM y G",
	"field-zone": "vöönd",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Eelmine nädal",
	"dateFormat-medium": "dd.MM.y G",
	"dateFormatItem-Hms": "H:mm.ss",
	"field-year-relative+0": "Sel aastal",
	"field-year-relative+1": "Järgmine aasta",
	"dateFormatItem-yMd": "d.M.y",
	"field-year-relative+-1": "Eelmine aasta",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "aasta",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "nädal",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "See nädal",
	"field-week-relative+1": "Järgmine nädal",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "See kuu",
	"dateFormatItem-H": "HH",
	"field-month": "kuu",
	"field-month-relative+1": "Järgmine kuu",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-mmss": "mm.ss",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d. MMM y",
	"field-second": "sekund",
	"field-day": "päev",
	"dateFormatItem-MEd": "E, d.M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d. MMMM y",
	"dateFormat-full": "EEEE, d. MMMM y G",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "E, d.M y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Eelmine kuu",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);