define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM.y.",
	"field-dayperiod": "pre podne/ popodne",
	"field-minute": "minut",
	"dateFormatItem-MMMEd": "E, dd. MMM",
	"field-day-relative+-1": "juče",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "prekjuče",
	"field-weekday": "dan u nedelji",
	"dateFormatItem-MMM": "LLL",
	"field-era": "era",
	"field-hour": "čas",
	"dateFormatItem-y": "y.",
	"dateFormatItem-Ed": "E, dd.",
	"dateFormatItem-yMMM": "MMM y.",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"dateFormat-long": "dd. MMMM y. G",
	"field-zone": "zona",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd.MM.y. G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "dd.MM.y.",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "godina",
	"field-week": "nedelja",
	"dateFormatItem-MMMd": "dd. MMM",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "mesec",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "dd. MMM y.",
	"field-second": "sekund",
	"field-day": "dan",
	"dateFormatItem-MEd": "E, dd.MM.",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd.MM.yy. GGGGG",
	"dateFormatItem-yMMMEd": "E, dd. MMM y.",
	"dateFormat-full": "EEEE, dd. MMMM y. G",
	"dateFormatItem-Md": "dd.MM.",
	"dateFormatItem-yMEd": "E, dd.MM.y.",
	"dateFormatItem-d": "d"
}
//end v1.x content
);