define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM.y.",
	"field-dayperiod": "Pirmspusd./pēcpusd.",
	"field-minute": "Minūtes",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "vakar",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "aizvakar",
	"field-weekday": "Nedēļas diena",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "Ēra",
	"field-hour": "Stundas",
	"dateFormatItem-y": "y. 'g'.",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-yMMM": "y. 'g'. MMM",
	"field-day-relative+0": "šodien",
	"field-day-relative+1": "rīt",
	"field-day-relative+2": "parīt",
	"dateFormat-long": "G y. 'gada' d. MMMM",
	"field-zone": "Laika josla",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Pagājušajā nedēļā",
	"dateFormat-medium": "G y. 'gada' d. MMM",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "Šogad",
	"field-year-relative+1": "Nākamgad",
	"dateFormatItem-yMd": "d.M.y.",
	"field-year-relative+-1": "Pagājušajā gadā",
	"dateFormatItem-yMMMM": "y. 'g'. MMMM",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Gads",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Nedēļa",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "Šonedēļ",
	"field-week-relative+1": "Nākamnedēļ",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month-relative+0": "Šomēnes",
	"dateFormatItem-H": "HH",
	"field-month": "Mēnesis",
	"field-month-relative+1": "Nākammēnes",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y. 'g'. d. MMM",
	"field-second": "Sekundes",
	"field-day": "Diena",
	"dateFormatItem-MEd": "E, dd.MM.",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, y. 'g'. d. MMM",
	"dateFormat-full": "EEEE, G y. 'gada' d. MMMM",
	"dateFormatItem-Md": "dd.MM.",
	"dateFormatItem-yMEd": "E, d.M.y.",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Pagājušajā mēnesī",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);