define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "AM/PM",
	"field-minute": "मिनिट",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "काल",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd-MM",
	"field-weekday": "आठवड्याचा दिवस",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "युग",
	"field-hour": "तास",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "आज",
	"field-day-relative+1": "उद्या",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "झोन",
	"dateFormatItem-Hm": "H-mm",
	"field-week-relative+-1": "मागील आठवडा",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "H-mm-ss",
	"field-year-relative+0": "या वर्षी",
	"field-year-relative+1": "पुढील वर्ष",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "मागील वर्ष",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "वर्ष",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "आठव़डा",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "हा आठवडा",
	"field-week-relative+1": "पुढील आठवडा",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "हा महिना",
	"dateFormatItem-H": "HH",
	"field-month": "महिना",
	"field-month-relative+1": "पुढील महिना",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "सेकंद",
	"field-day": "दिवस",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d-M-yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "मागील महिना",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);