define(
//begin v1.x content
{
	"field-dayperiod": "समय अवधि",
	"dateFormatItem-yyyyMMMEd": "E, d MMM Gy",
	"dayPeriods-format-wide-pm": "अपराह्न",
	"field-minute": "मिनट",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "बीता कल",
	"field-weekday": "सप्ताह का दिन",
	"field-day-relative+-2": "बीता परसों",
	"dateFormatItem-MMM": "MMM",
	"months-standAlone-narrow": [
		"ज",
		"फ़",
		"मा",
		"अ",
		"म",
		"जू",
		"जु",
		"अ",
		"सि",
		"अ",
		"न",
		"दि"
	],
	"field-era": "युग",
	"dateFormatItem-Gy": "Gy",
	"field-hour": "घंटा",
	"dayPeriods-format-wide-am": "पूर्वाह्न",
	"dateFormatItem-y": "Gy",
	"timeFormat-full": "h:mm:ss a zzzz",
	"dateFormatItem-yyyy": "Gy",
	"months-standAlone-abbr": [
		"फर्वादिन",
		"ओर्दिवेहेस्ट",
		"खोरर्दाद",
		"टिर",
		"मोरदाद",
		"शाहरीवर्",
		"मेहर",
		"अवन",
		"अज़र",
		"डे",
		"बहमन",
		"ईस्फन्द्"
	],
	"dateFormatItem-Ed": "d E",
	"field-day-relative+0": "आज",
	"field-day-relative+1": "कल",
	"days-standAlone-narrow": [
		"र",
		"सो",
		"मं",
		"बु",
		"गु",
		"शु",
		"श"
	],
	"field-day-relative+2": "परसों",
	"dateFormatItem-GyMMMd": "d MMM Gy",
	"dateFormat-long": "d MMMM Gy",
	"timeFormat-medium": "h:mm:ss a",
	"field-zone": "क्षेत्र",
	"field-week-relative+-1": "पिछले सप्ताह",
	"dateFormat-medium": "dd-MM-y G",
	"dayPeriods-format-narrow-pm": "अपराह्न",
	"field-year-relative+0": "इस वर्ष",
	"field-year-relative+1": "अगले वर्ष",
	"field-year-relative+-1": "पिछले वर्ष",
	"field-year": "वर्ष",
	"dateFormatItem-yyyyQQQQ": "QQQQ Gy",
	"dayPeriods-format-narrow-am": "पूर्वाह्न",
	"months-standAlone-wide": [
		"फर्वादिन",
		"ओर्दिवेहेस्ट",
		"खोरर्दाद",
		"टिर",
		"मोरदाद",
		"शाहरीवर्",
		"मेहर",
		"अवन",
		"अज़र",
		"डे",
		"बहमन",
		"ईस्फन्द्"
	],
	"field-week": "सप्ताह",
	"dateFormatItem-yyyyMMMd": "d MMM Gy",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMEd": "E, d/M/y G",
	"field-week-relative+0": "इस सप्ताह",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+1": "अगले सप्ताह",
	"months-format-abbr": [
		"फर्वादिन",
		"ओर्दिवेहेस्ट",
		"खोरर्दाद",
		"टिर",
		"मोरदाद",
		"शाहरीवर्",
		"मेहर",
		"अवन",
		"अज़र",
		"डे",
		"बहमन",
		"ईस्फन्द्"
	],
	"timeFormat-long": "h:mm:ss a z",
	"field-month-relative+0": "इस माह",
	"field-month": "मास",
	"field-month-relative+1": "अगले माह",
	"timeFormat-short": "h:mm a",
	"days-format-abbr": [
		"रवि.",
		"सोम.",
		"मंगल.",
		"बुध.",
		"बृह.",
		"शुक्र.",
		"शनि."
	],
	"field-second": "सेकेंड",
	"dateFormatItem-GyMMMEd": "E, d MMM Gy",
	"dateFormatItem-GyMMM": "MMM Gy",
	"field-day": "दिन",
	"dateFormatItem-yyyyQQQ": "QQQ Gy",
	"dateFormatItem-MEd": "E, d/M",
	"days-standAlone-short": [
		"र",
		"सो",
		"मं",
		"बु",
		"गु",
		"शु",
		"श"
	],
	"dateFormat-short": "d-M-y G",
	"dateFormatItem-yyyyM": "M-y G",
	"dateFormat-full": "EEEE, d MMMM Gy",
	"dateFormatItem-Md": "d/M",
	"months-format-wide": [
		"फर्वादिन",
		"ओर्दिवेहेस्ट",
		"खोरर्दाद",
		"टिर",
		"मोरदाद",
		"शाहरीवर्",
		"मेहर",
		"अवन",
		"अज़र",
		"डे",
		"बहमन",
		"ईस्फन्द्"
	],
	"days-format-short": [
		"र",
		"सो",
		"मं",
		"बु",
		"गु",
		"शु",
		"श"
	],
	"dateFormatItem-yyyyMMM": "MMM Gy",
	"field-month-relative+-1": "पिछला माह",
	"quarters-format-wide": [
		"तिमाही",
		"दूसरी तिमाही",
		"तीसरी तिमाही",
		"चौथी तिमाही"
	],
	"days-format-wide": [
		"रविवार",
		"सोमवार",
		"मंगलवार",
		"बुधवार",
		"बृहस्पतिवार",
		"शुक्रवार",
		"शनिवार"
	]
}
//end v1.x content
);