define(
//begin v1.x content
{
	"dateFormat-medium": "U MMM d",
	"field-second": "Detik",
	"field-year-relative+-1": "Tahun lalu",
	"field-week": "Minggu",
	"field-month-relative+-1": "Bulan lalu",
	"field-day-relative+-1": "Kemarin",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-day-relative+-2": "Kemarin lusa",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-year": "Tahun",
	"field-week-relative+0": "Minggu ini",
	"months-standAlone-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-week-relative+1": "Minggu berikutnya",
	"field-minute": "Menit",
	"field-week-relative+-1": "Minggu lalu",
	"field-day-relative+0": "Hari Ini",
	"field-hour": "Jam",
	"field-day-relative+1": "Besok",
	"dateFormat-long": "U MMMM d",
	"field-day-relative+2": "Lusa",
	"field-day": "Hari",
	"field-month-relative+0": "Bulan ini",
	"field-month-relative+1": "Bulan berikutnya",
	"field-dayperiod": "Siang/Malam",
	"field-month": "Bulan",
	"dateFormat-short": "y-M-d",
	"months-format-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-era": "Era",
	"field-year-relative+0": "Tahun ini",
	"field-year-relative+1": "Tahun depan",
	"months-format-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormat-full": "EEEE, U MMMM dd",
	"field-weekday": "Hari dalam Seminggu",
	"field-zone": "Zona Waktu"
}
//end v1.x content
);