define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "Tageshälfti",
	"field-minute": "Minuute",
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "geschter",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd.MM.",
	"field-day-relative+-2": "vorgeschter",
	"field-weekday": "Wuchetag",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Epoche",
	"field-hour": "Schtund",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-yMMdd": "dd.MM.y",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "hüt",
	"field-day-relative+1": "moorn",
	"field-day-relative+2": "übermoorn",
	"dateFormat-long": "d. MMMM y G",
	"field-zone": "Zone",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-MMd": "d.MM.",
	"dateFormat-medium": "dd.MM.y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Jaar",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"field-week": "Wuche",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-HHmm": "HH:mm",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-H": "H",
	"field-month": "Monet",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"field-second": "Sekunde",
	"field-day": "Tag",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"dateFormat-full": "EEEE, d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-d": "d"
}
//end v1.x content
);