define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "སྔ་ཆ/ཕྱི་ཆ་",
	"field-minute": "སྐར་མ",
	"dateFormatItem-MMMEd": "E, སྤྱི་LLL ཚེ་d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ཁ་ཙ་",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "ཁ་ཉིམ",
	"field-weekday": "བདུན་ཕྲག་གི་ཉིམ",
	"dateFormatItem-MMM": "སྤྱི་LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "དུས་བསྐལ",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "ཆུ་ཚོད",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "y སྤྱི་ཟླ་MMM",
	"field-day-relative+0": "ད་རིས་",
	"field-day-relative+1": "ནངས་པ་",
	"field-day-relative+2": "གནངས་ཚེ",
	"dateFormat-long": "G སྤྱི་ལོ་y MMMM ཚེས་ dd",
	"field-zone": "དུས་ཀུལ",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "G སྤྱི་ལོ་y ཟླ་MMM ཚེས་dd",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "y-M-d",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ལོ",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "བདུན་ཕྲག",
	"dateFormatItem-MMMd": "སྤྱི་LLL ཚེ་d",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "ཟླ་ཝ་",
	"dateFormatItem-H": "ཆུ་ཚོད་HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "སྐར་ཆཱ་",
	"field-day": "ཚེས་",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yMMMEd": "གཟའ་E, ལོy ཟླ་MMM ཚེ་d",
	"dateFormat-full": "EEEE, G སྤྱི་ལོ་y MMMM ཚེས་dd",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "ཆུ་ཚོད་h a"
}
//end v1.x content
);