define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "صبح/رات",
	"field-minute": "مِنَٹ",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "راتھ",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-weekday": "ہفتُک دۄہ",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"field-era": "دور",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "گٲنٛٹہٕ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "اَز",
	"field-day-relative+1": "پگاہ",
	"dateFormat-long": "MMMM d, y G",
	"field-zone": "زون",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ؤری",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "ہفتہٕ",
	"dateFormatItem-GGGGyMMMMEEEEdd": "EEEE,dd MMMM GGGGy",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "d-MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "رٮ۪تھ",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "سٮ۪کَنڑ",
	"field-day": "دۄہ",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "M/d/yy GGGGG",
	"dateFormatItem-yMMMEd": "EEE, MMM d, y",
	"dateFormat-full": "EEEE, MMMM d, y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "EEE, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);