define(
//begin v1.x content
{
	"field-second": "ሰከንድ",
	"field-year-relative+-1": "ያለፈው ዓመት",
	"field-week": "ሳምንት",
	"field-month-relative+-1": "ያለፈው ወር",
	"field-day-relative+-1": "ትናንት",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"field-day-relative+-2": "ከትናንት ወዲያ",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-standAlone-wide": [
		"መስከረም",
		"ጥቅምት",
		"ኅዳር",
		"ታኅሣሥ",
		"ጥር",
		"የካቲት",
		"መጋቢት",
		"ሚያዝያ",
		"ግንቦት",
		"ሰኔ",
		"ሐምሌ",
		"ነሐሴ",
		"ጳጉሜን"
	],
	"field-year": "ዓመት",
	"field-week-relative+0": "በዚህ ሣምንት",
	"months-standAlone-abbr": [
		"መስከ",
		"ጥቅም",
		"ኅዳር",
		"ታኅሣ",
		"ጥር",
		"የካቲ",
		"መጋቢ",
		"ሚያዝ",
		"ግንቦ",
		"ሰኔ",
		"ሐምሌ",
		"ነሐሴ",
		"ጳጉሜ"
	],
	"field-week-relative+1": "የሚቀጥለው ሳምንት",
	"field-minute": "ደቂቃ",
	"field-week-relative+-1": "ባለፈው ሳምንት",
	"field-day-relative+0": "ዛሬ",
	"field-hour": "ሰዓት",
	"field-day-relative+1": "ነገ",
	"field-day-relative+2": "ከነገ ወዲያ",
	"field-day": "ቀን",
	"field-month-relative+0": "በዚህ ወር",
	"field-month-relative+1": "የሚቀጥለው ወር",
	"field-dayperiod": "ጥዋት/ከሰዓት",
	"field-month": "ወር",
	"months-format-wide": [
		"መስከረም",
		"ጥቅምት",
		"ኅዳር",
		"ታኅሣሥ",
		"ጥር",
		"የካቲት",
		"መጋቢት",
		"ሚያዝያ",
		"ግንቦት",
		"ሰኔ",
		"ሐምሌ",
		"ነሐሴ",
		"ጳጉሜን"
	],
	"field-era": "ዘመን",
	"field-year-relative+0": "በዚህ ዓመት",
	"field-year-relative+1": "የሚቀጥለው ዓመት",
	"months-format-abbr": [
		"መስከ",
		"ጥቅም",
		"ኅዳር",
		"ታኅሣ",
		"ጥር",
		"የካቲ",
		"መጋቢ",
		"ሚያዝ",
		"ግንቦ",
		"ሰኔ",
		"ሐምሌ",
		"ነሐሴ",
		"ጳጉሜ"
	],
	"field-weekday": "አዘቦት",
	"field-zone": "የሰዓት ሰቅ"
}
//end v1.x content
);