define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "ጥዋት/ከሰዓት",
	"field-minute": "ደቂቃ",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ትናንት",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "ከትናንት ወዲያ",
	"field-weekday": "አዘቦት",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "ዘመን",
	"field-hour": "ሰዓት",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ዛሬ",
	"field-day-relative+1": "ነገ",
	"field-day-relative+2": "ከነገ ወዲያ",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "የሰዓት ሰቅ",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "ባለፈው ሳምንት",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "በዚህ ዓመት",
	"field-year-relative+1": "የሚቀጥለው ዓመት",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "ያለፈው ዓመት",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ዓመት",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "ሳምንት",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"field-week-relative+0": "በዚህ ሣምንት",
	"field-week-relative+1": "የሚቀጥለው ሳምንት",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "በዚህ ወር",
	"dateFormatItem-H": "H",
	"field-month": "ወር",
	"field-month-relative+1": "የሚቀጥለው ወር",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "ሰከንድ",
	"field-day": "ቀን",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E፣ MMM d y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E፣ d/M/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "ያለፈው ወር",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);