define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "AM/PM",
	"field-minute": "મિનિટ",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ગઈકાલ",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd-MM",
	"field-day-relative+-2": "ગઈકાસ પહેસાંનો દિવસ",
	"field-weekday": "અઠવાડિયાનો દિવસ",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "યુગ",
	"field-hour": "કલાક",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM-y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "આજ",
	"field-day-relative+1": "આવતીકાલ",
	"field-day-relative+2": "પરમ દિવસ",
	"dateFormat-long": "d MMMM, y G",
	"field-zone": "વિસ્તાર",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "છેલ્લું અઠવાડિયું",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-year-relative+0": "આ વર્ષ",
	"field-year-relative+1": "આગલું વર્ષ",
	"dateFormatItem-yMd": "d/M/y",
	"field-year-relative+-1": "પાછલું વર્ષ",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "વર્ષ",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "અહવાડિયું",
	"dateFormatItem-MMMd": "d MMM",
	"field-week-relative+0": "આ અઠવાડિયે",
	"field-week-relative+1": "આગલા અઠવાડિયે",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month-relative+0": "આ મહિને",
	"dateFormatItem-H": "HH",
	"field-month": "મહિનો",
	"field-month-relative+1": "આગલો મહીનો",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d, MMM y",
	"field-second": "ક્ષણ",
	"field-day": "દિવસ",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "d-MM-yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM, y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "છેલ્લો મહિનો",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);