define(
//begin v1.x content
{
	"field-dayperiod": "пре подне/поподне",
	"dayPeriods-format-wide-pm": "поподне",
	"field-minute": "минут",
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "јуче",
	"field-weekday": "дан у недељи",
	"dateFormatItem-hms": "hh.mm.ss a",
	"field-day-relative+-2": "прекјуче",
	"days-standAlone-wide": [
		"недеља",
		"понедељак",
		"уторак",
		"среда",
		"четвртак",
		"петак",
		"субота"
	],
	"field-era": "ера",
	"field-hour": "час",
	"dayPeriods-format-wide-am": "пре подне",
	"quarters-standAlone-abbr": [
		"К1",
		"К2",
		"К3",
		"К4"
	],
	"dateFormatItem-y": "y.",
	"timeFormat-full": "HH.mm.ss zzzz",
	"months-standAlone-abbr": [
		"Тишри",
		"Хешван",
		"Кислев",
		"Тевет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нисан",
		"Ијар",
		"Сиван",
		"Тамуз",
		"Ав",
		"Елул"
	],
	"dateFormatItem-Ed": "E d.",
	"field-day-relative+0": "данас",
	"field-day-relative+1": "сутра",
	"days-standAlone-narrow": [
		"н",
		"п",
		"у",
		"с",
		"ч",
		"п",
		"с"
	],
	"field-day-relative+2": "прекосутра",
	"dateFormat-long": "dd. MMMM y. G",
	"timeFormat-medium": "HH.mm.ss",
	"field-zone": "зона",
	"dateFormatItem-Hm": "HH.mm",
	"field-week-relative+-1": "Прошле недеље",
	"dateFormat-medium": "dd.MM.y. G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"field-year-relative+0": "Ове године",
	"field-year-relative+1": "Следеће године",
	"quarters-standAlone-wide": [
		"Прво тромесечје",
		"Друго тромесечје",
		"Треће тромесечје",
		"Четврто тромесечје"
	],
	"field-year-relative+-1": "Прошле године",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "година",
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"months-standAlone-wide": [
		"Тишри",
		"Хешван",
		"Кислев",
		"Тевет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нисан",
		"Ијар",
		"Сиван",
		"Тамуз",
		"Ав",
		"Елул"
	],
	"field-week": "недеља",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "Ове недеље",
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-week-relative+1": "Следеће недеље",
	"months-format-abbr": [
		"Тишри",
		"Хешван",
		"Кислев",
		"Тевет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нисан",
		"Ијар",
		"Сиван",
		"Тамуз",
		"Ав",
		"Елул"
	],
	"timeFormat-long": "HH.mm.ss z",
	"field-month-relative+0": "Овог месеца",
	"field-month": "месец",
	"field-month-relative+1": "Следећег месеца",
	"timeFormat-short": "HH.mm",
	"quarters-format-abbr": [
		"К1",
		"К2",
		"К3",
		"К4"
	],
	"days-format-abbr": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"days-format-narrow": [
		"н",
		"п",
		"у",
		"с",
		"ч",
		"п",
		"с"
	],
	"field-second": "секунд",
	"field-day": "дан",
	"dateFormatItem-MEd": "E, M-d",
	"days-standAlone-short": [
		"не",
		"по",
		"ут",
		"ср",
		"че",
		"пе",
		"су"
	],
	"dateFormatItem-hm": "hh.mm a",
	"days-standAlone-abbr": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"dateFormat-short": "d.M.yy. GGGGG",
	"dateFormatItem-Md": "d/M",
	"dateFormat-full": "EEEE, dd. MMMM y. G",
	"months-format-wide": [
		"Тишри",
		"Хешван",
		"Кислев",
		"Тевет",
		"Шеват",
		"Адар I",
		"Адар",
		"Нисан",
		"Ијар",
		"Сиван",
		"Тамуз",
		"Ав",
		"Елул"
	],
	"days-format-short": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"months-format-wide-leap": "Адар II",
	"field-month-relative+-1": "Прошлог месеца",
	"quarters-format-wide": [
		"Прво тромесечје",
		"Друго тромесечје",
		"Треће тромесечје",
		"Четврто тромесечје"
	],
	"days-format-wide": [
		"недеља",
		"понедељак",
		"уторак",
		"среда",
		"четвртак",
		"петак",
		"субота"
	],
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);