define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "Өдрийн цаг",
	"field-minute": "Минут",
	"dateFormatItem-MMMEd": "E MMM d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "Өчигдөр",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "Уржигдар",
	"field-weekday": "Гариг",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"field-era": "Эрин",
	"dateTimeFormat-medium": "{1} {0}",
	"field-hour": "Цаг",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "dd E",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "Өнөөдөр",
	"field-day-relative+1": "Маргааш",
	"field-day-relative+2": "Нөгөөдөр",
	"dateFormat-long": "G y 'оны' MMM 'сарын' d",
	"field-zone": "Бүс",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "G y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "y-M-d",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Жил",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "Долоо хоног",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "y 'оны' QQQQ",
	"field-month": "Сар",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "Хором",
	"field-day": "Өдөр",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yMMMEd": "E, y MMM d",
	"dateFormat-full": "EEEE, G y 'оны' MMM 'сарын' dd",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);