define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM/y",
	"field-dayperiod": "ДП/ПП",
	"field-minute": "хвіліна",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "учора",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "пазаўчора",
	"field-weekday": "дзень тыдня",
	"dateFormatItem-MMM": "LLL",
	"field-era": "эра",
	"field-hour": "гадзіна",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "сёння",
	"field-day-relative+1": "заўтра",
	"field-day-relative+2": "паслязаўтра",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Zone",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-yMd": "d.M.y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "год",
	"field-week": "тыдзень",
	"dateFormatItem-MMMMEd": "MMMM d, EEEE",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "месяц",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "секунда",
	"field-day": "дзень",
	"dateFormatItem-MEd": "E, d MMM",
	"dateFormatItem-hm": "h.mm a",
	"dateFormat-short": "d.M.yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);