define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "ເຊົ້າ/ແລງ",
	"field-minute": "ນາທີ",
	"dateFormatItem-MMMEd": "E MMM d",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "ວານນີ້",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "ມື້ກ່ອນ",
	"field-weekday": "ມື້ຂອງອາທິດ",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"field-era": "ສະໄໝ",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-hour": "ຊົ່ວໂມງ",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "ມື້ນີ້",
	"field-day-relative+1": "ມື້ອື່ນ",
	"field-day-relative+2": "ມື້ຮື",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "ເວລາຕາມເຂດ",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "y-M-d",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ປີ",
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "ອາທິດ",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "ເດືອນ",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "y MMM d",
	"field-second": "ວິນາທີ",
	"field-day": "ມື້",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E, y MMM d",
	"dateFormat-full": "EEEEທີ d MMMM y G",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h ໂມງa"
}
//end v1.x content
);