define({ root:

//begin v1.x content
{
	"days-standAlone-short": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-weekday": "Day of the Week",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yMEd": "y-MM-dd, E",
	"dateFormatItem-GyMMMEd": "G y MMM d, E",
	"dateFormatItem-MMMEd": "MMM d, E",
	"eraNarrow": [
		"BCE",
		"CE"
	],
	"days-format-short": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}",
	"dateFormat-long": "y MMMM d",
	"months-format-wide": [
		"Month1",
		"Month2",
		"Month3",
		"Month4",
		"Month5",
		"Month6",
		"Month7",
		"Month8",
		"Month9",
		"Month10",
		"Month11",
		"Month12"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "PM",
	"dateFormat-full": "y MMMM d, EEEE",
	"dateFormatItem-Md": "MM-dd",
	"dayPeriods-format-abbr-am": "AM",
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})",
	"dateFormatItem-yMd": "y-MM-dd",
	"field-era": "Era",
	"dateFormatItem-yM": "y-MM",
	"months-standAlone-wide": [
		"Month1",
		"Month2",
		"Month3",
		"Month4",
		"Month5",
		"Month6",
		"Month7",
		"Month8",
		"Month9",
		"Month10",
		"Month11",
		"Month12"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dateFormatItem-yQQQQ": "y QQQQ",
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Year",
	"dateFormatItem-yMMM": "y MMM",
	"dateTimeFormats-appendItem-Era": "{1} {0}",
	"field-hour": "Hour",
	"months-format-abbr": [
		"Month1",
		"Month2",
		"Month3",
		"Month4",
		"Month5",
		"Month6",
		"Month7",
		"Month8",
		"Month9",
		"Month10",
		"Month11",
		"Month12"
	],
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})",
	"field-day-relative+0": "Today",
	"field-day-relative+1": "Tomorrow",
	"dateFormatItem-GyMMMd": "G y MMM d",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"Month1",
		"Month2",
		"Month3",
		"Month4",
		"Month5",
		"Month6",
		"Month7",
		"Month8",
		"Month9",
		"Month10",
		"Month11",
		"Month12"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"BCE",
		"CE"
	],
	"field-minute": "Minute",
	"field-dayperiod": "Dayperiod",
	"days-standAlone-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Yesterday",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1} {0}",
	"dayPeriods-format-narrow-am": "AM",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-day": "Day",
	"days-format-wide": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"field-zone": "Zone",
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-hm": "h:mm a",
	"dateTimeFormats-appendItem-Year": "{1} {0}",
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})",
	"dayPeriods-format-abbr-pm": "PM",
	"days-format-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"eraNames": [
		"BCE",
		"CE"
	],
	"dateFormatItem-yMMMd": "y MMM d",
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"W",
		"T",
		"F",
		"S"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"W",
		"T",
		"F",
		"S"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "Month",
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})",
	"dayPeriods-format-wide-am": "AM",
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})",
	"dateFormat-short": "y-MM-dd",
	"field-second": "Second",
	"dateFormatItem-yMMMEd": "y MMM d, E",
	"dateFormatItem-Ed": "d, E",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-week": "Week",
	"dateFormat-medium": "y MMM d",
	"dayPeriods-format-narrow-pm": "PM",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "G y MMM"
}
//end v1.x content
,
	"aa": true,
	"af": true,
	"agq": true,
	"ak": true,
	"am": true,
	"ar": true,
	"ar-dz": true,
	"ar-iq": true,
	"ar-jo": true,
	"ar-lb": true,
	"ar-ma": true,
	"ar-sy": true,
	"ar-tn": true,
	"as": true,
	"asa": true,
	"ast": true,
	"az": true,
	"az-cyrl": true,
	"bas": true,
	"be": true,
	"bem": true,
	"bez": true,
	"bg": true,
	"bm": true,
	"bn": true,
	"bn-in": true,
	"bo": true,
	"br": true,
	"brx": true,
	"bs": true,
	"bs-cyrl": true,
	"byn": true,
	"ca": true,
	"cgg": true,
	"chr": true,
	"cs": true,
	"cy": true,
	"da": true,
	"dav": true,
	"de": true,
	"de-at": true,
	"dje": true,
	"dua": true,
	"dyo": true,
	"dz": true,
	"ebu": true,
	"ee": true,
	"el": true,
	"en": true,
	"en-150": true,
	"en-au": true,
	"en-be": true,
	"en-bw": true,
	"en-bz": true,
	"en-dsrt": true,
	"en-gb": true,
	"en-hk": true,
	"en-ie": true,
	"en-in": true,
	"en-mt": true,
	"en-nz": true,
	"en-pk": true,
	"en-sg": true,
	"en-za": true,
	"en-zw": true,
	"eo": true,
	"es": true,
	"es-419": true,
	"es-ar": true,
	"es-cl": true,
	"es-co": true,
	"es-ec": true,
	"es-gt": true,
	"es-hn": true,
	"es-pa": true,
	"es-pe": true,
	"es-pr": true,
	"es-us": true,
	"et": true,
	"eu": true,
	"ewo": true,
	"fa": true,
	"fa-af": true,
	"ff": true,
	"fi": true,
	"fil": true,
	"fo": true,
	"fr": true,
	"fr-be": true,
	"fr-ca": true,
	"fr-ch": true,
	"fur": true,
	"ga": true,
	"gd": true,
	"gl": true,
	"gsw": true,
	"gu": true,
	"guz": true,
	"gv": true,
	"ha": true,
	"ha-sd": true,
	"haw": true,
	"he": true,
	"hi": true,
	"hr": true,
	"hu": true,
	"hy": true,
	"id": true,
	"ig": true,
	"ii": true,
	"is": true,
	"it": true,
	"it-ch": true,
	"ja": true,
	"jgo": true,
	"jmc": true,
	"ka": true,
	"kab": true,
	"kam": true,
	"kde": true,
	"kea": true,
	"khq": true,
	"ki": true,
	"kk": true,
	"kkj": true,
	"kl": true,
	"kln": true,
	"km": true,
	"kn": true,
	"ko": true,
	"kok": true,
	"ks": true,
	"ksb": true,
	"ksf": true,
	"ksh": true,
	"ku-tr": true,
	"kw": true,
	"ky": true,
	"lag": true,
	"lg": true,
	"ln": true,
	"lo": true,
	"lt": true,
	"lu": true,
	"luo": true,
	"luy": true,
	"lv": true,
	"mas": true,
	"mer": true,
	"mfe": true,
	"mg": true,
	"mgh": true,
	"mgo": true,
	"mk": true,
	"ml": true,
	"mn": true,
	"mo": true,
	"mr": true,
	"ms": true,
	"ms-latn-bn": true,
	"mt": true,
	"mua": true,
	"my": true,
	"naq": true,
	"nb": true,
	"nd": true,
	"ne": true,
	"ne-in": true,
	"nl": true,
	"nl-be": true,
	"nmg": true,
	"nn": true,
	"nnh": true,
	"nus": true,
	"nyn": true,
	"om": true,
	"or": true,
	"os": true,
	"pa": true,
	"pa-arab": true,
	"pa-pk": true,
	"pl": true,
	"ps": true,
	"pt": true,
	"pt-pt": true,
	"rm": true,
	"rn": true,
	"ro": true,
	"rof": true,
	"ru": true,
	"ru-ua": true,
	"rw": true,
	"rwk": true,
	"sah": true,
	"saq": true,
	"sbp": true,
	"se": true,
	"seh": true,
	"ses": true,
	"sg": true,
	"sh": true,
	"shi": true,
	"shi-latn": true,
	"si": true,
	"sk": true,
	"sl": true,
	"sn": true,
	"so": true,
	"sq": true,
	"sr": true,
	"sr-cyrl-ba": true,
	"sr-latn": true,
	"sr-latn-me": true,
	"ssy": true,
	"sv": true,
	"sw": true,
	"swc": true,
	"ta": true,
	"te": true,
	"teo": true,
	"th": true,
	"ti": true,
	"ti-er": true,
	"to": true,
	"tr": true,
	"twq": true,
	"tzm": true,
	"uk": true,
	"ur": true,
	"uz": true,
	"uz-af": true,
	"uz-latn": true,
	"vai": true,
	"vai-latn": true,
	"vi": true,
	"vo": true,
	"vun": true,
	"wae": true,
	"xog": true,
	"yav": true,
	"yo": true,
	"zh": true,
	"zh-hans-hk": true,
	"zh-hans-mo": true,
	"zh-hans-sg": true,
	"zh-hant": true,
	"zh-hant-hk": true,
	"zh-hant-mo": true,
	"zh-hk": true,
	"zh-mo": true,
	"zh-tw": true,
	"zu": true
});