define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "pre podne/popodne",
	"field-minute": "minut",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "juče",
	"dateFormatItem-hms": "hh.mm.ss a",
	"dateFormatItem-MMdd": "MM-dd",
	"dateFormatItem-yQQQ": "QQQ. y",
	"field-day-relative+-2": "prekjuče",
	"field-weekday": "dan u nedelji",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "era",
	"field-hour": "čas",
	"dateFormatItem-y": "y.",
	"dateFormatItem-MMMdd": "dd.MMM",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-yMMdd": "dd.MM.y",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y.",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"dateFormat-long": "dd. MMMM y. G",
	"field-zone": "zona",
	"dateFormatItem-Hm": "HH.mm",
	"field-week-relative+-1": "Prošle nedelje",
	"dateFormat-medium": "dd.MM.y. G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"field-year-relative+0": "Ove godine",
	"field-year-relative+1": "Sledeće godine",
	"dateFormatItem-yMd": "d. M. y.",
	"field-year-relative+-1": "Prošle godine",
	"dateFormatItem-yMMMM": "MMMM y.",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "godina",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "nedelja",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+0": "Ove nedelje",
	"field-week-relative+1": "Sledeće nedelje",
	"dateFormatItem-yQQQQ": "QQQQ. y",
	"field-month-relative+0": "Ovog meseca",
	"dateFormatItem-H": "HH",
	"field-month": "mesec",
	"field-month-relative+1": "Sledećeg meseca",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d. MMM y.",
	"field-second": "sekund",
	"field-day": "dan",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-hm": "hh.mm a",
	"dateFormat-short": "d.M.yy. GGGGG",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"dateFormat-full": "EEEE, dd. MMMM y. G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d. M. y.",
	"dateFormatItem-d": "d",
	"field-month-relative+-1": "Prošlog meseca",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);